# -*- coding: utf-8 -*-
"""Contenu des pages du compte avocat : connexion et tableau de bord "mon
profil". Meme principe que verification_content.py : contenu statique
versionne dans le depot, traduit en 4 langues, consomme par build.py.

Rappel de la chaine complete : le compte (email + mot de passe) est cree
des la demande de verification d'identite elle-meme -- voir
verification_content.py (formulaire) / api/verification-request.js
(pre-creation bloquee) / api/verification-confirm.js et
api/verification-decide.js (activation a la confirmation). Il n'y a donc
plus de page separee de "creation de compte" apres coup : une fois
l'identite confirmee, l'avocat se connecte directement avec le mot de passe
deja choisi. La page de connexion utilise Supabase Auth (email + mot de
passe classique). La page "mon profil" ne permet de modifier QUE le
contenu complementaire (bio, photo, liens) et les coordonnees AFFICHEES
(email/telephone de contact) -- jamais les donnees source du registre
officiel, qui restent en lecture seule et proviennent toujours du registre
cantonal."""

LOGIN = {
    "fr": {
        "title": "Connexion avocat",
        "intro": "Connectez-vous pour accéder à votre profil et le compléter.",
        "field_email": "Email",
        "field_password": "Mot de passe",
        "submit": "Se connecter",
        "submitting": "Connexion en cours...",
        "forgot_password_link": "Mot de passe oublié ?",
        "forgot_password_title": "Réinitialiser mon mot de passe",
        "forgot_password_intro": "Indiquez votre email, nous vous enverrons un lien pour choisir un nouveau mot de passe.",
        "forgot_password_submit": "Envoyer le lien",
        "forgot_password_success": "Si un compte existe avec cet email, un lien de réinitialisation vient de lui être envoyé.",
        "forgot_password_back": "Retour à la connexion",
        "error_generic": "Une erreur est survenue. Réessayez.",
        "error_invalid_credentials": "Email ou mot de passe incorrect.",
        "no_account_hint": "Vous êtes avocat(e) et n'avez pas encore de compte ?",
        "no_account_link": "Vérifiez votre identité pour en créer un",
    },
    "de": {
        "title": "Anwaltsanmeldung",
        "intro": "Melden Sie sich an, um auf Ihr Profil zuzugreifen und es zu vervollständigen.",
        "field_email": "E-Mail",
        "field_password": "Passwort",
        "submit": "Anmelden",
        "submitting": "Anmeldung läuft...",
        "forgot_password_link": "Passwort vergessen?",
        "forgot_password_title": "Mein Passwort zurücksetzen",
        "forgot_password_intro": "Geben Sie Ihre E-Mail-Adresse an, wir senden Ihnen einen Link zur Wahl eines neuen Passworts.",
        "forgot_password_submit": "Link senden",
        "forgot_password_success": "Falls ein Konto mit dieser E-Mail besteht, wurde soeben ein Link zum Zurücksetzen gesendet.",
        "forgot_password_back": "Zurück zur Anmeldung",
        "error_generic": "Ein Fehler ist aufgetreten. Versuchen Sie es erneut.",
        "error_invalid_credentials": "E-Mail oder Passwort falsch.",
        "no_account_hint": "Sind Sie Anwältin oder Anwalt und haben noch kein Konto?",
        "no_account_link": "Bestätigen Sie Ihre Identität, um eines zu erstellen",
    },
    "it": {
        "title": "Accesso avvocati",
        "intro": "Accedete per raggiungere il vostro profilo e completarlo.",
        "field_email": "Email",
        "field_password": "Password",
        "submit": "Accedere",
        "submitting": "Accesso in corso...",
        "forgot_password_link": "Password dimenticata?",
        "forgot_password_title": "Reimpostare la mia password",
        "forgot_password_intro": "Indicate la vostra email, vi invieremo un link per scegliere una nuova password.",
        "forgot_password_submit": "Invia il link",
        "forgot_password_success": "Se esiste un account con questa email, un link di reimpostazione è appena stato inviato.",
        "forgot_password_back": "Torna all'accesso",
        "error_generic": "Si è verificato un errore. Riprovate.",
        "error_invalid_credentials": "Email o password errati.",
        "no_account_hint": "Siete avvocati e non avete ancora un account?",
        "no_account_link": "Verificate la vostra identità per crearne uno",
    },
    "en": {
        "title": "Lawyer login",
        "intro": "Log in to access your profile and complete it.",
        "field_email": "Email",
        "field_password": "Password",
        "submit": "Log in",
        "submitting": "Logging in...",
        "forgot_password_link": "Forgot your password?",
        "forgot_password_title": "Reset my password",
        "forgot_password_intro": "Enter your email, we'll send you a link to choose a new password.",
        "forgot_password_submit": "Send link",
        "forgot_password_success": "If an account exists with this email, a reset link has just been sent to it.",
        "forgot_password_back": "Back to login",
        "error_generic": "Something went wrong. Please try again.",
        "error_invalid_credentials": "Incorrect email or password.",
        "no_account_hint": "Are you a lawyer without an account yet?",
        "no_account_link": "Verify your identity to create one",
    },
}

PROFILE = {
    "fr": {
        "title": "Mon profil",
        "intro": "Complétez votre fiche avec une présentation, une photo et vos coordonnées de contact. Ces informations sont vérifiées manuellement avant publication.",
        "loading": "Chargement de votre profil...",
        "not_logged_in": "Vous devez être connecté(e) pour accéder à cette page.",
        "login_link": "Se connecter",
        "section_registry_title": "Informations du registre officiel",
        "section_registry_note": "Ces informations proviennent du registre cantonal officiel et ne peuvent pas être modifiées ici. Pour signaler une erreur, utilisez le formulaire de correction.",
        "section_edit_title": "Contenu complémentaire",
        "field_bio": "Présentation (bio)",
        "field_bio_help": "3000 caractères maximum.",
        "field_photo": "Photo de profil",
        "field_photo_help": "Formats acceptés : JPG ou PNG, 5 Mo maximum. Cette photo sera publique une fois approuvée.",
        "field_display_email": "Email affiché sur votre fiche",
        "field_display_email_help": "Peut différer de l'email de connexion. Laissez vide pour ne rien afficher.",
        "field_display_telephone": "Téléphone affiché sur votre fiche",
        "field_link_website": "Site internet",
        "field_link_linkedin": "LinkedIn",
        "submit": "Soumettre pour vérification",
        "submitting": "Envoi en cours...",
        "success_submitted": "Merci, votre soumission a été enregistrée et sera examinée sous peu.",
        "status_title": "Statut de votre dernière soumission",
        "status_pending": "En attente de vérification",
        "status_approved": "Publiée",
        "status_rejected": "Refusée",
        "status_none": "Aucune soumission pour le moment.",
        "logout": "Se déconnecter",
        "error_generic": "Une erreur est survenue. Réessayez ou écrivez-nous à gregoiregiuliano@hotmail.com.",
        "error_bio_too_long": "La présentation ne doit pas dépasser 3000 caractères.",
        "error_photo_too_large": "Photo trop volumineuse (5 Mo maximum).",
        "error_invalid_photo_type": "Format de photo non accepté.",
        "error_invalid_email": "Merci d'indiquer un email valide.",
    },
    "de": {
        "title": "Mein Profil",
        "intro": "Vervollständigen Sie Ihren Eintrag mit einer Vorstellung, einem Foto und Ihren Kontaktdaten. Diese Angaben werden vor der Veröffentlichung manuell geprüft.",
        "loading": "Ihr Profil wird geladen...",
        "not_logged_in": "Sie müssen angemeldet sein, um auf diese Seite zuzugreifen.",
        "login_link": "Anmelden",
        "section_registry_title": "Angaben aus dem offiziellen Register",
        "section_registry_note": "Diese Angaben stammen aus dem offiziellen kantonalen Register und können hier nicht geändert werden. Um einen Fehler zu melden, nutzen Sie das Korrekturformular.",
        "section_edit_title": "Ergänzender Inhalt",
        "field_bio": "Vorstellung (Bio)",
        "field_bio_help": "Maximal 3000 Zeichen.",
        "field_photo": "Profilfoto",
        "field_photo_help": "Zulässige Formate: JPG oder PNG, maximal 5 MB. Dieses Foto wird nach Genehmigung öffentlich sichtbar.",
        "field_display_email": "Auf Ihrem Eintrag angezeigte E-Mail",
        "field_display_email_help": "Kann von der Anmelde-E-Mail abweichen. Leer lassen, um nichts anzuzeigen.",
        "field_display_telephone": "Auf Ihrem Eintrag angezeigtes Telefon",
        "field_link_website": "Webseite",
        "field_link_linkedin": "LinkedIn",
        "submit": "Zur Überprüfung einreichen",
        "submitting": "Wird gesendet...",
        "success_submitted": "Vielen Dank, Ihre Einreichung wurde erfasst und wird in Kürze geprüft.",
        "status_title": "Status Ihrer letzten Einreichung",
        "status_pending": "Wird überprüft",
        "status_approved": "Veröffentlicht",
        "status_rejected": "Abgelehnt",
        "status_none": "Noch keine Einreichung vorhanden.",
        "logout": "Abmelden",
        "error_generic": "Ein Fehler ist aufgetreten. Versuchen Sie es erneut oder schreiben Sie uns an gregoiregiuliano@hotmail.com.",
        "error_bio_too_long": "Die Vorstellung darf 3000 Zeichen nicht überschreiten.",
        "error_photo_too_large": "Foto zu gross (maximal 5 MB).",
        "error_invalid_photo_type": "Fotoformat nicht zulässig.",
        "error_invalid_email": "Bitte geben Sie eine gültige E-Mail-Adresse an.",
    },
    "it": {
        "title": "Il mio profilo",
        "intro": "Completate la vostra scheda con una presentazione, una foto e i vostri recapiti. Queste informazioni sono verificate manualmente prima della pubblicazione.",
        "loading": "Caricamento del vostro profilo...",
        "not_logged_in": "Dovete essere connessi per accedere a questa pagina.",
        "login_link": "Accedere",
        "section_registry_title": "Informazioni dal registro ufficiale",
        "section_registry_note": "Queste informazioni provengono dal registro cantonale ufficiale e non possono essere modificate qui. Per segnalare un errore, utilizzate il modulo di correzione.",
        "section_edit_title": "Contenuto complementare",
        "field_bio": "Presentazione (bio)",
        "field_bio_help": "Massimo 3000 caratteri.",
        "field_photo": "Foto del profilo",
        "field_photo_help": "Formati accettati: JPG o PNG, massimo 5 MB. Questa foto sarà pubblica una volta approvata.",
        "field_display_email": "Email visualizzata sulla vostra scheda",
        "field_display_email_help": "Può differire dall'email di accesso. Lasciate vuoto per non mostrare nulla.",
        "field_display_telephone": "Telefono visualizzato sulla vostra scheda",
        "field_link_website": "Sito web",
        "field_link_linkedin": "LinkedIn",
        "submit": "Sottoporre per la verifica",
        "submitting": "Invio in corso...",
        "success_submitted": "Grazie, la vostra sottomissione è stata registrata e sarà esaminata a breve.",
        "status_title": "Stato della vostra ultima sottomissione",
        "status_pending": "In attesa di verifica",
        "status_approved": "Pubblicata",
        "status_rejected": "Rifiutata",
        "status_none": "Nessuna sottomissione per il momento.",
        "logout": "Disconnettersi",
        "error_generic": "Si è verificato un errore. Riprovate o scriveteci a gregoiregiuliano@hotmail.com.",
        "error_bio_too_long": "La presentazione non deve superare 3000 caratteri.",
        "error_photo_too_large": "Foto troppo grande (massimo 5 MB).",
        "error_invalid_photo_type": "Formato foto non accettato.",
        "error_invalid_email": "Indicate un'email valida.",
    },
    "en": {
        "title": "My profile",
        "intro": "Complete your listing with a presentation, a photo, and your contact details. This information is manually reviewed before publication.",
        "loading": "Loading your profile...",
        "not_logged_in": "You must be logged in to access this page.",
        "login_link": "Log in",
        "section_registry_title": "Official register information",
        "section_registry_note": "This information comes from the official cantonal register and cannot be changed here. To report an error, use the correction form.",
        "section_edit_title": "Complementary content",
        "field_bio": "Presentation (bio)",
        "field_bio_help": "3000 characters maximum.",
        "field_photo": "Profile photo",
        "field_photo_help": "Accepted formats: JPG or PNG, 5 MB maximum. This photo will be public once approved.",
        "field_display_email": "Email shown on your listing",
        "field_display_email_help": "Can differ from your login email. Leave blank to display nothing.",
        "field_display_telephone": "Phone shown on your listing",
        "field_link_website": "Website",
        "field_link_linkedin": "LinkedIn",
        "submit": "Submit for review",
        "submitting": "Submitting...",
        "success_submitted": "Thank you, your submission has been recorded and will be reviewed shortly.",
        "status_title": "Status of your latest submission",
        "status_pending": "Awaiting review",
        "status_approved": "Published",
        "status_rejected": "Rejected",
        "status_none": "No submission yet.",
        "logout": "Log out",
        "error_generic": "Something went wrong. Try again or write to us at gregoiregiuliano@hotmail.com.",
        "error_bio_too_long": "The presentation must not exceed 3000 characters.",
        "error_photo_too_large": "Photo too large (5 MB maximum).",
        "error_invalid_photo_type": "Photo format not accepted.",
        "error_invalid_email": "Please provide a valid email.",
    },
}
