# -*- coding: utf-8 -*-
"""Contenu du formulaire de depot d'avis et du widget d'affichage sur les
fiches avocat. Meme principe que vitrine_content.py : contenu statique
versionne dans le depot, traduit en 4 langues, consomme par build.py."""

FORM = {
    "fr": {
        "title": "Laisser un avis",
        "intro": "Vous avez été client(e) d'un avocat ou d'une avocate référencé(e) sur Legatis ? Partagez votre expérience. Chaque avis est vérifié manuellement avant publication.",
        "step1_title": "1. Retrouvez l'avocat(e) concerné(e)",
        "step1_help": "Recherchez son nom pour rattacher votre avis à sa fiche du registre officiel.",
        "step1_search_placeholder": "Nom de l'avocat(e)...",
        "step1_selected": "Fiche sélectionnée :",
        "step1_change": "Changer",
        "step1_not_found": "Vous ne trouvez pas la fiche ? Écrivez-nous à contact@legatis.ch.",
        "step2_title": "2. Votre note",
        "field_rating": "Note globale",
        "step3_title": "3. Votre avis",
        "field_title": "Titre (optionnel)",
        "field_title_placeholder": "Résumez votre expérience en quelques mots",
        "field_body": "Votre expérience",
        "field_body_placeholder": "Décrivez votre expérience avec cet avocat ou cette avocate : accompagnement, communication, résultat...",
        "field_reviewer_name": "Votre nom (optionnel, affiché publiquement)",
        "field_reviewer_name_placeholder": "Laissez vide pour rester anonyme",
        "step4_title": "4. Votre email",
        "field_contact_email": "Email (privé, jamais publié, utilisé uniquement pour valider l'avis)",
        "consent": "Je confirme que cet avis reflète une expérience réelle et personnelle avec cet avocat ou cette avocate.",
        "submit": "Envoyer mon avis",
        "submitting": "Envoi en cours...",
        "success_title": "Avis envoyé",
        "success_text": "Merci. Votre avis sera publié après vérification, généralement sous quelques jours.",
        "error_generic": "Une erreur est survenue. Réessayez ou écrivez-nous à contact@legatis.ch.",
        "error_missing_match": "Merci de sélectionner l'avocat(e) concerné(e) avant de continuer.",
        "error_missing_rating": "Merci de donner une note.",
        "error_missing_body": "Merci de décrire votre expérience.",
        "error_missing_consent": "Merci de confirmer qu'il s'agit d'une expérience réelle.",
    },
    "de": {
        "title": "Eine Bewertung abgeben",
        "intro": "Waren Sie Mandant(in) einer auf Legatis aufgeführten Anwältin oder eines Anwalts? Teilen Sie Ihre Erfahrung. Jede Bewertung wird vor der Veröffentlichung manuell geprüft.",
        "step1_title": "1. Finden Sie die betreffende Person",
        "step1_help": "Suchen Sie den Namen, um Ihre Bewertung mit dem Eintrag im offiziellen Register zu verknüpfen.",
        "step1_search_placeholder": "Name der Anwältin/des Anwalts...",
        "step1_selected": "Ausgewählter Eintrag:",
        "step1_change": "Ändern",
        "step1_not_found": "Sie finden den Eintrag nicht? Schreiben Sie uns an contact@legatis.ch.",
        "step2_title": "2. Ihre Bewertung",
        "field_rating": "Gesamtbewertung",
        "step3_title": "3. Ihre Erfahrung",
        "field_title": "Titel (optional)",
        "field_title_placeholder": "Fassen Sie Ihre Erfahrung kurz zusammen",
        "field_body": "Ihre Erfahrung",
        "field_body_placeholder": "Beschreiben Sie Ihre Erfahrung mit dieser Anwältin/diesem Anwalt: Betreuung, Kommunikation, Ergebnis...",
        "field_reviewer_name": "Ihr Name (optional, öffentlich sichtbar)",
        "field_reviewer_name_placeholder": "Leer lassen, um anonym zu bleiben",
        "step4_title": "4. Ihre E-Mail",
        "field_contact_email": "E-Mail (privat, wird nie veröffentlicht, dient nur zur Bestätigung der Bewertung)",
        "consent": "Ich bestätige, dass diese Bewertung eine echte, persönliche Erfahrung mit dieser Anwältin/diesem Anwalt wiedergibt.",
        "submit": "Bewertung senden",
        "submitting": "Wird gesendet...",
        "success_title": "Bewertung gesendet",
        "success_text": "Vielen Dank. Ihre Bewertung wird nach Prüfung veröffentlicht, in der Regel innerhalb weniger Tage.",
        "error_generic": "Ein Fehler ist aufgetreten. Versuchen Sie es erneut oder schreiben Sie uns an contact@legatis.ch.",
        "error_missing_match": "Bitte wählen Sie zuerst die betreffende Person aus.",
        "error_missing_rating": "Bitte geben Sie eine Bewertung ab.",
        "error_missing_body": "Bitte beschreiben Sie Ihre Erfahrung.",
        "error_missing_consent": "Bitte bestätigen Sie, dass es sich um eine echte Erfahrung handelt.",
    },
    "it": {
        "title": "Lasciare una recensione",
        "intro": "Siete stati clienti di un avvocato o un'avvocata presente su Legatis? Condividete la vostra esperienza. Ogni recensione viene verificata manualmente prima della pubblicazione.",
        "step1_title": "1. Trovate l'avvocato/a interessato/a",
        "step1_help": "Cercate il nome per collegare la vostra recensione alla scheda del registro ufficiale.",
        "step1_search_placeholder": "Nome dell'avvocato/a...",
        "step1_selected": "Scheda selezionata:",
        "step1_change": "Cambia",
        "step1_not_found": "Non trovate la scheda? Scriveteci a contact@legatis.ch.",
        "step2_title": "2. La vostra valutazione",
        "field_rating": "Valutazione complessiva",
        "step3_title": "3. La vostra esperienza",
        "field_title": "Titolo (facoltativo)",
        "field_title_placeholder": "Riassumete la vostra esperienza in poche parole",
        "field_body": "La vostra esperienza",
        "field_body_placeholder": "Descrivete la vostra esperienza con questo avvocato/a: assistenza, comunicazione, risultato...",
        "field_reviewer_name": "Il vostro nome (facoltativo, mostrato pubblicamente)",
        "field_reviewer_name_placeholder": "Lasciate vuoto per restare anonimi",
        "step4_title": "4. La vostra email",
        "field_contact_email": "Email (privata, mai pubblicata, usata solo per validare la recensione)",
        "consent": "Confermo che questa recensione riflette un'esperienza reale e personale con questo avvocato/a.",
        "submit": "Invia la mia recensione",
        "submitting": "Invio in corso...",
        "success_title": "Recensione inviata",
        "success_text": "Grazie. La vostra recensione sarà pubblicata dopo la verifica, generalmente entro qualche giorno.",
        "error_generic": "Si è verificato un errore. Riprovate o scriveteci a contact@legatis.ch.",
        "error_missing_match": "Selezionate l'avvocato/a interessato/a prima di continuare.",
        "error_missing_rating": "Indicate una valutazione.",
        "error_missing_body": "Descrivete la vostra esperienza.",
        "error_missing_consent": "Confermate che si tratta di un'esperienza reale.",
    },
    "en": {
        "title": "Leave a review",
        "intro": "Were you a client of a lawyer listed on Legatis? Share your experience. Every review is manually checked before publishing.",
        "step1_title": "1. Find the lawyer",
        "step1_help": "Search their name to link your review to their listing in the official register.",
        "step1_search_placeholder": "Lawyer's name...",
        "step1_selected": "Selected listing:",
        "step1_change": "Change",
        "step1_not_found": "Can't find the listing? Email us at contact@legatis.ch.",
        "step2_title": "2. Your rating",
        "field_rating": "Overall rating",
        "step3_title": "3. Your experience",
        "field_title": "Title (optional)",
        "field_title_placeholder": "Summarise your experience in a few words",
        "field_body": "Your experience",
        "field_body_placeholder": "Describe your experience with this lawyer: support, communication, outcome...",
        "field_reviewer_name": "Your name (optional, shown publicly)",
        "field_reviewer_name_placeholder": "Leave blank to stay anonymous",
        "step4_title": "4. Your email",
        "field_contact_email": "Email (private, never published, used only to confirm the review)",
        "consent": "I confirm this review reflects a real, personal experience with this lawyer.",
        "submit": "Send my review",
        "submitting": "Sending...",
        "success_title": "Review sent",
        "success_text": "Thank you. Your review will be published after checking, usually within a few days.",
        "error_generic": "Something went wrong. Try again or email us at contact@legatis.ch.",
        "error_missing_match": "Please select the lawyer before continuing.",
        "error_missing_rating": "Please give a rating.",
        "error_missing_body": "Please describe your experience.",
        "error_missing_consent": "Please confirm this is a real experience.",
    },
}

# Strings pour le widget d'affichage des avis sur les fiches avocat (fetch
# cote client, voir templates/_reviews_widget.html).
WIDGET = {
    "fr": {
        "heading": "Avis",
        "cta": "Laisser un avis",
        "empty": "Aucun avis pour l'instant.",
        "loading": "Chargement des avis...",
        "based_on_one": "avis",
        "based_on_many": "avis",
        "anonymous": "Anonyme",
    },
    "de": {
        "heading": "Bewertungen",
        "cta": "Bewertung abgeben",
        "empty": "Noch keine Bewertungen.",
        "loading": "Bewertungen werden geladen...",
        "based_on_one": "Bewertung",
        "based_on_many": "Bewertungen",
        "anonymous": "Anonym",
    },
    "it": {
        "heading": "Recensioni",
        "cta": "Lascia una recensione",
        "empty": "Ancora nessuna recensione.",
        "loading": "Caricamento delle recensioni...",
        "based_on_one": "recensione",
        "based_on_many": "recensioni",
        "anonymous": "Anonimo",
    },
    "en": {
        "heading": "Reviews",
        "cta": "Leave a review",
        "empty": "No reviews yet.",
        "loading": "Loading reviews...",
        "based_on_one": "review",
        "based_on_many": "reviews",
        "anonymous": "Anonymous",
    },
}
