# -*- coding: utf-8 -*-
"""Contenu du formulaire de verification d'identite + creation de compte
(revendication de fiche) et de la page de confirmation. Meme principe que
review_content.py : contenu statique versionne dans le depot, traduit en 4
langues, consomme par build.py.

Le mot de passe du compte est choisi des cette demande initiale (voir
api/verification-request.js) -- "creer son compte" est desormais la
premiere action du demandeur, avant meme la confirmation de son identite.
Les 3 methodes de verification (email/telephone/document) sont TOUJOURS
proposees, meme quand un email ou un telephone est deja connu pour la
fiche : c'est le demandeur qui choisit, au cas ou l'un de ces contacts
serait errone. Seule la coherence du choix "email" (l'adresse fournie doit
matcher exactement celle deja publiee) est verifiee cote serveur -- ce
module ne contient que le texte affiche, jamais la logique de decision."""

FORM = {
    "fr": {
        "title": "Vérifier mon identité",
        "intro": "Une fiche du registre officiel vous concerne ? Créez votre compte et confirmez votre identité pour prouver qu'il s'agit bien de vous.",
        "step1_title": "1. Retrouvez votre fiche",
        "step1_help": "Recherchez votre nom pour le rattacher à l'entrée du registre officiel.",
        "step1_search_placeholder": "Votre nom...",
        "step1_selected": "Fiche sélectionnée :",
        "step1_change": "Changer",
        "step1_not_found": "Vous ne trouvez pas votre fiche ? Écrivez-nous à gregoiregiuliano@hotmail.com.",
        "step_account_title": "2. Créez votre compte",
        "step_account_intro": "Ce compte reste bloqué tant que votre identité n'est pas confirmée : il s'active automatiquement dès que c'est fait, sans étape supplémentaire.",
        "field_account_email": "Email professionnel",
        "field_account_email_help": "C'est l'email avec lequel vous vous connecterez. S'il correspond à celui déjà publié sur le registre pour cette fiche, vous pourrez être vérifié(e) automatiquement par email.",
        "field_password": "Mot de passe",
        "field_password_help": "8 caractères minimum.",
        "field_password_confirm": "Confirmer le mot de passe",
        "consent_marketing": "J'accepte de recevoir d'autres emails de Legatis (actualités, conseils, nouvelles fonctionnalités). Facultatif, sans lien avec la création du compte. Vous pouvez décliner.",
        "step_method_title": "3. Comment souhaitez-vous être vérifié(e) ?",
        "step_method_help": "Vous pouvez choisir le téléphone ou l'envoi de documents même si un email est déjà enregistré pour cette fiche, par exemple s'il n'est plus à jour.",
        "method_option_email": "Par email",
        "method_option_email_desc": "Un lien de confirmation à usage unique est envoyé à l'adresse déjà publiée sur le registre pour cette fiche. Cliquer dessus active votre compte immédiatement.",
        "method_option_phone": "Par téléphone",
        "method_option_phone_desc": "Nous vous appellerons au numéro déjà publié sur votre fiche pour confirmer votre identité. Cette vérification manuelle peut prendre plusieurs jours.",
        "method_option_document": "Par document",
        "method_option_document_desc": "Envoyez votre carte de légitimation d'avocat(e) (ou à défaut votre brevet d'avocat) ainsi qu'un selfie. Examinés manuellement puis supprimés immédiatement après la décision, quel que soit son sens. Cette vérification manuelle peut prendre plusieurs jours.",
        "field_contact_note": "Vos disponibilités (optionnel)",
        "field_contact_note_placeholder": "Par exemple : joignable en semaine après 17h",
        "field_document": "Carte de légitimation d'avocat(e), ou à défaut votre brevet d'avocat",
        "field_document_help": "Formats acceptés : JPG, PNG ou PDF, 8 Mo maximum.",
        "field_selfie": "Un selfie de vous",
        "field_selfie_help": "Formats acceptés : JPG ou PNG, 8 Mo maximum. Utilisé uniquement pour comparer avec la photo du document, puis supprimé immédiatement après décision.",
        "consent_account": "Je confirme être la personne concernée par cette fiche et je crée mon compte avocat sur cette base.",
        "consent_document": "Je confirme que ces documents me concernent personnellement. Je comprends qu'ils seront supprimés immédiatement après la décision de vérification, quel que soit son sens.",
        "submit_email": "Créer mon compte et envoyer le lien",
        "submit_phone": "Créer mon compte et demander un rappel",
        "submit_document": "Créer mon compte et envoyer mes documents",
        "submitting": "Envoi en cours...",
        "success_email_title": "Compte créé : vérifiez vos emails",
        "success_email_text": "Votre compte a été créé et reste bloqué pour l'instant. Un lien de confirmation a été envoyé à l'adresse déjà enregistrée pour cette fiche. Vérifiez votre boîte de réception et cliquez dessus pour activer votre compte.",
        "success_email_spam_note": "📩 Vous ne le voyez pas d'ici quelques minutes ? Regardez dans votre dossier spams / courrier indésirable. C'est fréquent avec ce type d'email.",
        "success_phone_title": "Compte créé : demande enregistrée",
        "success_phone_text": "Votre compte a été créé et reste bloqué pour l'instant. Nous vous appellerons au numéro déjà publié sur votre fiche ; cette vérification manuelle peut prendre plusieurs jours. Votre compte sera activé dès la confirmation de votre identité.",
        "success_document_title": "Compte créé : documents envoyés",
        "success_document_text": "Votre compte a été créé et reste bloqué pour l'instant. Vos documents seront examinés puis supprimés immédiatement après la décision ; cette vérification manuelle peut prendre plusieurs jours. Votre compte sera activé dès la confirmation de votre identité.",
        "error_generic": "Une erreur est survenue. Réessayez ou écrivez-nous à gregoiregiuliano@hotmail.com.",
        "error_missing_match": "Merci de sélectionner votre fiche avant de continuer.",
        "error_missing_account_email": "Merci d'indiquer votre email professionnel.",
        "error_invalid_account_email": "Merci d'indiquer un email valide.",
        "error_password_too_short": "Le mot de passe doit contenir au moins 8 caractères.",
        "error_password_mismatch": "Les mots de passe ne correspondent pas.",
        "error_email_already_registered": "Un compte existe déjà avec cet email. Essayez de vous connecter, ou utilisez un autre email.",
        "error_email_mismatch": "Cet email ne correspond pas à celui déjà publié pour cette fiche. Choisissez plutôt la vérification par téléphone ou par document.",
        "error_method_unavailable": "Cette méthode de vérification n'est pas disponible pour cette fiche.",
        "error_missing_document": "Merci de joindre votre carte de légitimation ou votre brevet d'avocat.",
        "error_missing_selfie": "Merci de joindre un selfie.",
        "error_file_too_large": "Fichier trop volumineux (8 Mo maximum).",
        "error_invalid_file_type": "Format de fichier non accepté.",
        "error_missing_consent": "Merci de confirmer la case ci-dessus.",
    },
    "de": {
        "title": "Meine Identität bestätigen",
        "intro": "Betrifft Sie ein Eintrag im offiziellen Register? Erstellen Sie Ihr Konto und bestätigen Sie Ihre Identität, um zu belegen, dass es sich um Sie handelt.",
        "step1_title": "1. Finden Sie Ihren Eintrag",
        "step1_help": "Suchen Sie Ihren Namen, um ihn mit dem Eintrag im offiziellen Register zu verknüpfen.",
        "step1_search_placeholder": "Ihr Name...",
        "step1_selected": "Ausgewählter Eintrag:",
        "step1_change": "Ändern",
        "step1_not_found": "Sie finden Ihren Eintrag nicht? Schreiben Sie uns an gregoiregiuliano@hotmail.com.",
        "step_account_title": "2. Erstellen Sie Ihr Konto",
        "step_account_intro": "Dieses Konto bleibt gesperrt, bis Ihre Identität bestätigt ist -- es wird danach automatisch aktiviert, ohne weiteren Schritt.",
        "field_account_email": "Berufliche E-Mail",
        "field_account_email_help": "Mit dieser E-Mail melden Sie sich an. Entspricht sie der bereits im Register für diesen Eintrag hinterlegten Adresse, können Sie automatisch per E-Mail überprüft werden.",
        "field_password": "Passwort",
        "field_password_help": "Mindestens 8 Zeichen.",
        "field_password_confirm": "Passwort bestätigen",
        "consent_marketing": "Ich bin damit einverstanden, weitere E-Mails von Legatis zu erhalten (Neuigkeiten, Tipps, neue Funktionen). Freiwillig, unabhängig von der Kontoerstellung. Sie können ablehnen.",
        "step_method_title": "3. Wie möchten Sie überprüft werden?",
        "step_method_help": "Sie können Telefon oder Dokumente wählen, auch wenn für diesen Eintrag bereits eine E-Mail hinterlegt ist -- zum Beispiel, falls diese nicht mehr aktuell ist.",
        "method_option_email": "Per E-Mail",
        "method_option_email_desc": "Ein einmaliger Bestätigungslink wird an die für diesen Eintrag bereits hinterlegte Adresse gesendet. Ein Klick darauf aktiviert Ihr Konto sofort.",
        "method_option_phone": "Per Telefon",
        "method_option_phone_desc": "Wir rufen Sie unter der bereits veröffentlichten Nummer an, um Ihre Identität zu bestätigen. Diese manuelle Überprüfung kann mehrere Tage dauern.",
        "method_option_document": "Per Dokument",
        "method_option_document_desc": "Senden Sie Ihren Anwaltsausweis (oder ersatzweise Ihr Anwaltspatent) sowie ein Selfie. Diese werden manuell geprüft und unmittelbar nach der Entscheidung gelöscht, unabhängig vom Ergebnis. Diese manuelle Überprüfung kann mehrere Tage dauern.",
        "field_contact_note": "Ihre Erreichbarkeit (optional)",
        "field_contact_note_placeholder": "Zum Beispiel: unter der Woche ab 17 Uhr erreichbar",
        "field_document": "Anwaltsausweis, oder ersatzweise Ihr Anwaltspatent",
        "field_document_help": "Zulässige Formate: JPG, PNG oder PDF, maximal 8 MB.",
        "field_selfie": "Ein Selfie von Ihnen",
        "field_selfie_help": "Zulässige Formate: JPG oder PNG, maximal 8 MB. Wird nur zum Abgleich mit dem Foto auf dem Dokument verwendet und danach sofort gelöscht.",
        "consent_account": "Ich bestätige, die von diesem Eintrag betroffene Person zu sein, und erstelle auf dieser Grundlage mein Anwaltskonto.",
        "consent_document": "Ich bestätige, dass diese Dokumente mich persönlich betreffen. Mir ist bewusst, dass sie unmittelbar nach der Entscheidung über die Überprüfung gelöscht werden, unabhängig vom Ergebnis.",
        "submit_email": "Konto erstellen und Link senden",
        "submit_phone": "Konto erstellen und Rückruf anfordern",
        "submit_document": "Konto erstellen und Dokumente senden",
        "submitting": "Wird gesendet...",
        "success_email_title": "Konto erstellt: prüfen Sie Ihre E-Mails",
        "success_email_text": "Ihr Konto wurde erstellt und bleibt vorerst gesperrt. Ein Bestätigungslink wurde an die für diesen Eintrag hinterlegte Adresse gesendet. Prüfen Sie Ihren Posteingang und klicken Sie darauf, um Ihr Konto zu aktivieren.",
        "success_email_spam_note": "📩 Sehen Sie ihn nach ein paar Minuten immer noch nicht? Schauen Sie in Ihrem Spam-Ordner nach. Das kommt bei dieser Art von E-Mail häufig vor.",
        "success_phone_title": "Konto erstellt: Anfrage erfasst",
        "success_phone_text": "Ihr Konto wurde erstellt und bleibt vorerst gesperrt. Wir rufen Sie unter der bereits veröffentlichten Nummer an; diese manuelle Überprüfung kann mehrere Tage dauern. Ihr Konto wird nach Bestätigung Ihrer Identität aktiviert.",
        "success_document_title": "Konto erstellt: Dokumente gesendet",
        "success_document_text": "Ihr Konto wurde erstellt und bleibt vorerst gesperrt. Ihre Dokumente werden geprüft und danach unmittelbar gelöscht; diese manuelle Überprüfung kann mehrere Tage dauern. Ihr Konto wird nach Bestätigung Ihrer Identität aktiviert.",
        "error_generic": "Ein Fehler ist aufgetreten. Versuchen Sie es erneut oder schreiben Sie uns an gregoiregiuliano@hotmail.com.",
        "error_missing_match": "Bitte wählen Sie zuerst Ihren Eintrag aus.",
        "error_missing_account_email": "Bitte geben Sie Ihre berufliche E-Mail-Adresse an.",
        "error_invalid_account_email": "Bitte geben Sie eine gültige E-Mail-Adresse an.",
        "error_password_too_short": "Das Passwort muss mindestens 8 Zeichen enthalten.",
        "error_password_mismatch": "Die Passwörter stimmen nicht überein.",
        "error_email_already_registered": "Es besteht bereits ein Konto mit dieser E-Mail. Versuchen Sie sich anzumelden oder verwenden Sie eine andere E-Mail.",
        "error_email_mismatch": "Diese E-Mail entspricht nicht der bereits für diesen Eintrag hinterlegten Adresse. Wählen Sie stattdessen die Überprüfung per Telefon oder Dokument.",
        "error_method_unavailable": "Diese Überprüfungsmethode ist für diesen Eintrag nicht verfügbar.",
        "error_missing_document": "Bitte fügen Sie Ihren Anwaltsausweis oder Ihr Anwaltspatent bei.",
        "error_missing_selfie": "Bitte fügen Sie ein Selfie bei.",
        "error_file_too_large": "Datei zu gross (maximal 8 MB).",
        "error_invalid_file_type": "Dateiformat nicht zulässig.",
        "error_missing_consent": "Bitte bestätigen Sie das obige Kästchen.",
    },
    "it": {
        "title": "Verificare la mia identità",
        "intro": "Una scheda del registro ufficiale vi riguarda? Create il vostro account e confermate la vostra identità per dimostrare che si tratta proprio di voi.",
        "step1_title": "1. Trovate la vostra scheda",
        "step1_help": "Cercate il vostro nome per collegarlo alla voce del registro ufficiale.",
        "step1_search_placeholder": "Il vostro nome...",
        "step1_selected": "Scheda selezionata:",
        "step1_change": "Cambia",
        "step1_not_found": "Non trovate la vostra scheda? Scriveteci a gregoiregiuliano@hotmail.com.",
        "step_account_title": "2. Create il vostro account",
        "step_account_intro": "Questo account resta bloccato finché la vostra identità non è confermata: si attiva automaticamente non appena ciò avviene, senza ulteriori passaggi.",
        "field_account_email": "Email professionale",
        "field_account_email_help": "È l'email con cui accederete. Se corrisponde a quella già pubblicata nel registro per questa scheda, potrete essere verificati automaticamente via email.",
        "field_password": "Password",
        "field_password_help": "Minimo 8 caratteri.",
        "field_password_confirm": "Confermare la password",
        "consent_marketing": "Accetto di ricevere altre email da Legatis (novità, consigli, nuove funzionalità). Facoltativo, indipendente dalla creazione dell'account. Potete rifiutare.",
        "step_method_title": "3. Come volete essere verificati?",
        "step_method_help": "Potete scegliere telefono o documento anche se per questa scheda è già registrata un'email, ad esempio se non è più aggiornata.",
        "method_option_email": "Via email",
        "method_option_email_desc": "Un link di conferma monouso viene inviato all'indirizzo già pubblicato nel registro per questa scheda. Cliccandoci sopra, il vostro account si attiva immediatamente.",
        "method_option_phone": "Via telefono",
        "method_option_phone_desc": "Vi chiameremo al numero già pubblicato sulla vostra scheda per confermare la vostra identità. Questa verifica manuale può richiedere diversi giorni.",
        "method_option_document": "Via documento",
        "method_option_document_desc": "Inviate la vostra tessera di legittimazione da avvocato/a (o in mancanza il vostro brevetto) insieme a un selfie. Esaminati manualmente e poi eliminati immediatamente dopo la decisione, qualunque essa sia. Questa verifica manuale può richiedere diversi giorni.",
        "field_contact_note": "La vostra disponibilità (facoltativo)",
        "field_contact_note_placeholder": "Ad esempio: raggiungibile nei giorni feriali dopo le 17",
        "field_document": "Tessera di legittimazione da avvocato/a, o in mancanza il vostro brevetto di avvocato/a",
        "field_document_help": "Formati accettati: JPG, PNG o PDF, massimo 8 MB.",
        "field_selfie": "Un selfie di voi stessi",
        "field_selfie_help": "Formati accettati: JPG o PNG, massimo 8 MB. Utilizzato solo per il confronto con la foto del documento, poi eliminato immediatamente dopo la decisione.",
        "consent_account": "Confermo di essere la persona interessata da questa scheda e creo il mio account avvocato su questa base.",
        "consent_document": "Confermo che questi documenti mi riguardano personalmente. Comprendo che verranno eliminati immediatamente dopo la decisione di verifica, qualunque essa sia.",
        "submit_email": "Creare il mio account e inviare il link",
        "submit_phone": "Creare il mio account e richiedere un richiamo",
        "submit_document": "Creare il mio account e inviare i miei documenti",
        "submitting": "Invio in corso...",
        "success_email_title": "Account creato: controllate le vostre email",
        "success_email_text": "Il vostro account è stato creato e resta bloccato per il momento. Un link di conferma è stato inviato all'indirizzo già registrato per questa scheda. Controllate la vostra casella di posta e cliccateci sopra per attivare il vostro account.",
        "success_email_spam_note": "📩 Non lo vedete dopo qualche minuto? Controllate nella cartella spam / posta indesiderata. È frequente con questo tipo di email.",
        "success_phone_title": "Account creato: richiesta registrata",
        "success_phone_text": "Il vostro account è stato creato e resta bloccato per il momento. Vi chiameremo al numero già pubblicato sulla vostra scheda; questa verifica manuale può richiedere diversi giorni. Il vostro account sarà attivato non appena la vostra identità sarà confermata.",
        "success_document_title": "Account creato: documenti inviati",
        "success_document_text": "Il vostro account è stato creato e resta bloccato per il momento. I vostri documenti saranno esaminati e poi eliminati immediatamente; questa verifica manuale può richiedere diversi giorni. Il vostro account sarà attivato non appena la vostra identità sarà confermata.",
        "error_generic": "Si è verificato un errore. Riprovate o scriveteci a gregoiregiuliano@hotmail.com.",
        "error_missing_match": "Selezionate la vostra scheda prima di continuare.",
        "error_missing_account_email": "Indicate la vostra email professionale.",
        "error_invalid_account_email": "Indicate un'email valida.",
        "error_password_too_short": "La password deve contenere almeno 8 caratteri.",
        "error_password_mismatch": "Le password non corrispondono.",
        "error_email_already_registered": "Esiste già un account con questa email. Provate ad accedere, oppure utilizzate un'altra email.",
        "error_email_mismatch": "Questa email non corrisponde a quella già pubblicata per questa scheda. Scegliete piuttosto la verifica via telefono o documento.",
        "error_method_unavailable": "Questo metodo di verifica non è disponibile per questa scheda.",
        "error_missing_document": "Allegate la vostra tessera di legittimazione o il vostro brevetto di avvocato/a.",
        "error_missing_selfie": "Allegate un selfie.",
        "error_file_too_large": "File troppo grande (massimo 8 MB).",
        "error_invalid_file_type": "Formato di file non accettato.",
        "error_missing_consent": "Confermate la casella qui sopra.",
    },
    "en": {
        "title": "Verify my identity",
        "intro": "Does a listing in the official register concern you? Create your account and confirm your identity to prove it's really you.",
        "step1_title": "1. Find your listing",
        "step1_help": "Search your name to link it to the entry in the official register.",
        "step1_search_placeholder": "Your name...",
        "step1_selected": "Selected listing:",
        "step1_change": "Change",
        "step1_not_found": "Can't find your listing? Write to us at gregoiregiuliano@hotmail.com.",
        "step_account_title": "2. Create your account",
        "step_account_intro": "This account stays locked until your identity is confirmed -- it activates automatically as soon as that happens, no extra step needed.",
        "field_account_email": "Professional email",
        "field_account_email_help": "This is the email you'll log in with. If it matches the one already published in the register for this listing, you can be verified automatically by email.",
        "field_password": "Password",
        "field_password_help": "8 characters minimum.",
        "field_password_confirm": "Confirm password",
        "consent_marketing": "I agree to receive other emails from Legatis (news, tips, new features). Optional, unrelated to account creation. You can decline.",
        "step_method_title": "3. How would you like to be verified?",
        "step_method_help": "You can choose phone or document even if an email is already on file for this listing -- for example if it's no longer up to date.",
        "method_option_email": "By email",
        "method_option_email_desc": "A one-time confirmation link is sent to the address already published in the register for this listing. Clicking it activates your account immediately.",
        "method_option_phone": "By phone",
        "method_option_phone_desc": "We'll call the number already published on your listing to confirm your identity. This manual check can take several days.",
        "method_option_document": "By document",
        "method_option_document_desc": "Send your bar identification card (or failing that, your law diploma) along with a selfie. Reviewed manually and then deleted immediately after the decision, whatever it is. This manual check can take several days.",
        "field_contact_note": "Your availability (optional)",
        "field_contact_note_placeholder": "For example: reachable weekdays after 5pm",
        "field_document": "Bar identification card, or failing that your law diploma",
        "field_document_help": "Accepted formats: JPG, PNG or PDF, 8 MB maximum.",
        "field_selfie": "A selfie of yourself",
        "field_selfie_help": "Accepted formats: JPG or PNG, 8 MB maximum. Used only to compare against the photo on the document, then deleted immediately after the decision.",
        "consent_account": "I confirm I am the person this listing concerns, and I am creating my lawyer account on this basis.",
        "consent_document": "I confirm these documents concern me personally. I understand they will be deleted immediately after the verification decision, whatever it is.",
        "submit_email": "Create my account and send the link",
        "submit_phone": "Create my account and request a callback",
        "submit_document": "Create my account and send my documents",
        "submitting": "Sending...",
        "success_email_title": "Account created: check your email",
        "success_email_text": "Your account was created and stays locked for now. A confirmation link has been sent to the address already on file for this listing. Check your inbox and click it to activate your account.",
        "success_email_spam_note": "📩 Don't see it after a few minutes? Check your spam / junk folder. This happens often with this type of email.",
        "success_phone_title": "Account created: request recorded",
        "success_phone_text": "Your account was created and stays locked for now. We'll call the number already published on your listing; this manual check can take several days. Your account will activate once your identity is confirmed.",
        "success_document_title": "Account created: documents sent",
        "success_document_text": "Your account was created and stays locked for now. Your documents will be reviewed and then deleted immediately; this manual check can take several days. Your account will activate once your identity is confirmed.",
        "error_generic": "Something went wrong. Try again or write to us at gregoiregiuliano@hotmail.com.",
        "error_missing_match": "Please select your listing before continuing.",
        "error_missing_account_email": "Please provide your professional email.",
        "error_invalid_account_email": "Please provide a valid email.",
        "error_password_too_short": "The password must be at least 8 characters long.",
        "error_password_mismatch": "The passwords do not match.",
        "error_email_already_registered": "An account already exists with this email. Try logging in, or use a different email.",
        "error_email_mismatch": "This email doesn't match the one already on file for this listing. Choose phone or document verification instead.",
        "error_method_unavailable": "This verification method isn't available for this listing.",
        "error_missing_document": "Please attach your bar identification card or law diploma.",
        "error_missing_selfie": "Please attach a selfie.",
        "error_file_too_large": "File too large (8 MB maximum).",
        "error_invalid_file_type": "File format not accepted.",
        "error_missing_consent": "Please confirm the checkbox above.",
    },
}

CONFIRM = {
    "fr": {
        "title": "Confirmation d'identité",
        "ok_title": "Identité confirmée",
        "ok_text": "Merci, votre identité a été confirmée et votre compte est désormais actif.",
        "expired_title": "Lien expiré",
        "expired_text": "Ce lien de vérification a expiré ou a déjà été utilisé. Vous pouvez refaire une demande depuis la page de vérification.",
        "error_title": "Lien invalide",
        "error_text": "Ce lien de vérification n'est pas valide. Vous pouvez refaire une demande depuis la page de vérification.",
        "back_link": "Retour à la page de vérification",
        "login_link": "Se connecter",
    },
    "de": {
        "title": "Identitätsbestätigung",
        "ok_title": "Identität bestätigt",
        "ok_text": "Vielen Dank, Ihre Identität wurde bestätigt und Ihr Konto ist jetzt aktiv.",
        "expired_title": "Link abgelaufen",
        "expired_text": "Dieser Bestätigungslink ist abgelaufen oder wurde bereits verwendet. Sie können auf der Überprüfungsseite eine neue Anfrage stellen.",
        "error_title": "Ungültiger Link",
        "error_text": "Dieser Bestätigungslink ist ungültig. Sie können auf der Überprüfungsseite eine neue Anfrage stellen.",
        "back_link": "Zurück zur Überprüfungsseite",
        "login_link": "Anmelden",
    },
    "it": {
        "title": "Conferma dell'identità",
        "ok_title": "Identità confermata",
        "ok_text": "Grazie, la vostra identità è stata confermata e il vostro account è ora attivo.",
        "expired_title": "Link scaduto",
        "expired_text": "Questo link di verifica è scaduto o è già stato utilizzato. Potete presentare una nuova richiesta dalla pagina di verifica.",
        "error_title": "Link non valido",
        "error_text": "Questo link di verifica non è valido. Potete presentare una nuova richiesta dalla pagina di verifica.",
        "back_link": "Torna alla pagina di verifica",
        "login_link": "Accedere",
    },
    "en": {
        "title": "Identity confirmation",
        "ok_title": "Identity confirmed",
        "ok_text": "Thank you, your identity has been confirmed and your account is now active.",
        "expired_title": "Link expired",
        "expired_text": "This verification link has expired or has already been used. You can submit a new request from the verification page.",
        "error_title": "Invalid link",
        "error_text": "This verification link is not valid. You can submit a new request from the verification page.",
        "back_link": "Back to the verification page",
        "login_link": "Log in",
    },
}
