"""Contenu du formulaire de demande de vitrine avocat (page publique) et des
options de personnalisation (templates, couleurs). Traduit en 4 langues,
suit le meme principe que guides_content.py / blog_content.py : contenu
statique versionne dans le depot, consomme par build.py."""

TEMPLATES = {
    "prestige": {
        "fr": {"label": "Prestige", "desc": "Sobre et formel, fond sombre, pour un cabinet établi."},
        "de": {"label": "Prestige", "desc": "Nüchtern und formell, dunkler Hintergrund, für eine etablierte Kanzlei."},
        "it": {"label": "Prestigio", "desc": "Sobrio e formale, sfondo scuro, per uno studio consolidato."},
        "en": {"label": "Prestige", "desc": "Formal and understated, dark hero, for an established practice."},
    },
    "moderne": {
        "fr": {"label": "Moderne", "desc": "Épuré et asymétrique, beaucoup d'espace blanc."},
        "de": {"label": "Modern", "desc": "Klar und asymmetrisch, viel Weissraum."},
        "it": {"label": "Moderno", "desc": "Essenziale e asimmetrico, molto spazio bianco."},
        "en": {"label": "Modern", "desc": "Clean and asymmetric, lots of white space."},
    },
    "chaleureux": {
        "fr": {"label": "Chaleureux", "desc": "Humain et accueillant, idéal en droit de la famille."},
        "de": {"label": "Herzlich", "desc": "Menschlich und einladend, ideal im Familienrecht."},
        "it": {"label": "Accogliente", "desc": "Umano e caloroso, ideale nel diritto di famiglia."},
        "en": {"label": "Warm", "desc": "Approachable and human, ideal for family law."},
    },
}

TEMPLATE_ORDER = ["prestige", "moderne", "chaleureux"]

ACCENT_COLORS = {
    "bordeaux": {"fr": "Bordeaux (couleur du site)", "de": "Bordeaux (Website-Farbe)", "it": "Bordeaux (colore del sito)", "en": "Bordeaux (site color)"},
    "encre": {"fr": "Encre (bleu-noir)", "de": "Tinte (Blauschwarz)", "it": "Inchiostro (blu-nero)", "en": "Ink (blue-black)"},
    "sapin": {"fr": "Sapin (vert)", "de": "Tannengruen", "it": "Verde abete", "en": "Pine (green)"},
    "ardoise": {"fr": "Ardoise (bleu-gris)", "de": "Schiefer (Blaugrau)", "it": "Ardesia (blu-grigio)", "en": "Slate (blue-grey)"},
}
ACCENT_ORDER = ["bordeaux", "encre", "sapin", "ardoise"]

PHOTO_FRAMES = {
    "cercle": {"fr": "Cercle classique", "de": "Klassischer Kreis", "it": "Cerchio classico", "en": "Classic circle"},
    "carre-arrondi": {"fr": "Carré arrondi", "de": "Abgerundetes Quadrat", "it": "Quadrato arrotondato", "en": "Rounded square"},
    "plein-cadre": {"fr": "Plein cadre", "de": "Vollformat", "it": "A pieno formato", "en": "Full frame"},
}
PHOTO_FRAME_ORDER = ["cercle", "carre-arrondi", "plein-cadre"]

FONT_STYLES = {
    "classique": {"fr": "Classique", "de": "Klassisch", "it": "Classico", "en": "Classic"},
    "elegant": {"fr": "Élégant", "de": "Elegant", "it": "Elegante", "en": "Elegant"},
    "contemporain": {"fr": "Contemporain", "de": "Zeitgenössisch", "it": "Contemporaneo", "en": "Contemporary"},
}
FONT_STYLE_ORDER = ["classique", "elegant", "contemporain"]

FORM = {
    "fr": {
        "title": "Demander votre vitrine gratuite",
        "intro": "Une page personnelle, hébergée sur Legatis, que vous pouvez mettre en avant sur votre fiche Google Business Profile ou votre propre site. Gratuit, sans engagement. Nous vérifions chaque demande avant publication.",
        "step1_title": "1. Retrouvez votre fiche",
        "step1_help": "Recherchez votre nom pour rattacher la vitrine à votre inscription au registre officiel (obligatoire).",
        "step1_search_placeholder": "Votre nom...",
        "step1_selected": "Fiche sélectionnée :",
        "step1_change": "Changer",
        "step1_not_found": "Vous ne trouvez pas votre fiche ? Écrivez-nous à contact@legatis.ch, votre canton n'est peut-être pas encore couvert.",
        "step2_title": "2. Choisissez un style",
        "step2_help": "Vous pourrez en changer plus tard, gratuitement, il suffit de nous écrire.",
        "step3_title": "3. Personnalisez votre page",
        "field_photo": "Photo professionnelle",
        "field_photo_help": "Format JPG ou PNG, 2 Mo maximum.",
        "field_role_titre": "Titre professionnel (optionnel)",
        "field_role_titre_placeholder": "Ex. : Avocate associee, specialiste FSA en droit du travail",
        "field_accroche": "Phrase d'accroche (courte)",
        "field_accroche_placeholder": "Ex. : Vous défendre avec rigueur et humanité.",
        "field_bio": "Présentation (texte libre)",
        "field_bio_placeholder": "Parcours, approche, ce qui vous distingue...",
        "field_citation": "Citation ou philosophie professionnelle (optionnel)",
        "field_specialites": "Vos domaines de compétence",
        "field_distinctions": "Distinctions ou publications (optionnel, une par ligne)",
        "field_site_web": "Site web (optionnel)",
        "field_linkedin": "LinkedIn (optionnel)",
        "field_instagram": "Instagram (optionnel)",
        "field_accent": "Couleur d'accent",
        "field_photo_frame": "Cadre de la photo",
        "field_style_titres": "Style des titres",
        "step4_title": "4. Informations pratiques (optionnel)",
        "step4_help": "Ces informations apparaissent sur votre page pour faciliter la prise de contact. Laissez vide ce que vous ne souhaitez pas afficher.",
        "field_adresse": "Adresse du cabinet",
        "field_adresse_placeholder": "Rue, numéro, code postal, ville",
        "field_horaires": "Horaires d'ouverture",
        "field_horaires_placeholder": "Ex. : Lu-Ve 8h30-18h00, sur rendez-vous",
        "field_whatsapp": "WhatsApp",
        "field_whatsapp_placeholder": "+41 79 000 00 00",
        "field_rdv_url": "Lien de prise de rendez-vous",
        "field_rdv_url_placeholder": "https://calendly.com/...",
        "field_video_url": "Vidéo de présentation (YouTube ou Vimeo)",
        "field_video_url_placeholder": "https://www.youtube.com/watch?v=...",
        "field_galerie": "Photos supplémentaires (cabinet, équipe)",
        "field_galerie_placeholder": "Une URL d'image par ligne, 4 maximum",
        "step5_title": "5. Vos coordonnées",
        "field_contact_email": "Email de contact (utilisé uniquement pour valider la demande)",
        "field_contact_phone": "Téléphone (optionnel, affiché sur la page si renseigné)",
        "consent": "Je confirme être la personne inscrite au registre sélectionnée ci-dessus, ou dûment mandatée pour agir en son nom.",
        "submit": "Envoyer ma demande",
        "submitting": "Envoi en cours...",
        "success_title": "Demande envoyée",
        "success_text": "Nous revenons vers vous par email sous quelques jours pour valider votre page avant publication.",
        "error_generic": "Une erreur est survenue. Réessayez ou écrivez-nous à contact@legatis.ch.",
        "error_missing_match": "Merci de sélectionner votre fiche dans le registre avant de continuer.",
        "error_missing_photo": "Une photo est requise.",
        "error_missing_consent": "Merci de confirmer votre identité professionnelle.",
    },
    "de": {
        "title": "Ihre kostenlose Vitrine beantragen",
        "intro": "Eine persönliche, auf Legatis gehostete Seite, die Sie auf Ihrem Google Unternehmensprofil oder Ihrer eigenen Website hervorheben können. Kostenlos, unverbindlich. Wir prüfen jede Anfrage vor der Veröffentlichung.",
        "step1_title": "1. Finden Sie Ihren Eintrag",
        "step1_help": "Suchen Sie Ihren Namen, um die Vitrine mit Ihrem Eintrag im offiziellen Register zu verknüpfen (erforderlich).",
        "step1_search_placeholder": "Ihr Name...",
        "step1_selected": "Ausgewählter Eintrag:",
        "step1_change": "Ändern",
        "step1_not_found": "Sie finden Ihren Eintrag nicht? Schreiben Sie uns an contact@legatis.ch, Ihr Kanton ist möglicherweise noch nicht erfasst.",
        "step2_title": "2. Wählen Sie einen Stil",
        "step2_help": "Sie können ihn später kostenlos ändern, schreiben Sie uns einfach.",
        "step3_title": "3. Gestalten Sie Ihre Seite",
        "field_photo": "Professionelles Foto",
        "field_photo_help": "JPG oder PNG, maximal 2 MB.",
        "field_role_titre": "Berufsbezeichnung (optional)",
        "field_role_titre_placeholder": "Z. B.: Partneranwaeltin, SAV-Fachanwaeltin Arbeitsrecht",
        "field_accroche": "Kurzer Slogan",
        "field_accroche_placeholder": "Z. B.: Ihre Interessen mit Sorgfalt und Menschlichkeit vertreten.",
        "field_bio": "Vorstellung (freier Text)",
        "field_bio_placeholder": "Werdegang, Ansatz, was Sie auszeichnet...",
        "field_citation": "Zitat oder berufliche Philosophie (optional)",
        "field_specialites": "Ihre Fachgebiete",
        "field_distinctions": "Auszeichnungen oder Publikationen (optional, eine pro Zeile)",
        "field_site_web": "Website (optional)",
        "field_linkedin": "LinkedIn (optional)",
        "field_instagram": "Instagram (optional)",
        "field_accent": "Akzentfarbe",
        "field_photo_frame": "Fotorahmen",
        "field_style_titres": "Titelstil",
        "step4_title": "4. Praktische Angaben (optional)",
        "step4_help": "Diese Angaben erscheinen auf Ihrer Seite, um die Kontaktaufnahme zu erleichtern. Lassen Sie leer, was Sie nicht anzeigen möchten.",
        "field_adresse": "Kanzleiadresse",
        "field_adresse_placeholder": "Strasse, Nummer, PLZ, Ort",
        "field_horaires": "Öffnungszeiten",
        "field_horaires_placeholder": "Z. B.: Mo-Fr 8.30-18.00 Uhr, nach Vereinbarung",
        "field_whatsapp": "WhatsApp",
        "field_whatsapp_placeholder": "+41 79 000 00 00",
        "field_rdv_url": "Link zur Terminvereinbarung",
        "field_rdv_url_placeholder": "https://calendly.com/...",
        "field_video_url": "Vorstellungsvideo (YouTube oder Vimeo)",
        "field_video_url_placeholder": "https://www.youtube.com/watch?v=...",
        "field_galerie": "Weitere Fotos (Kanzlei, Team)",
        "field_galerie_placeholder": "Eine Bild-URL pro Zeile, maximal 4",
        "step5_title": "5. Ihre Kontaktdaten",
        "field_contact_email": "Kontakt-E-Mail (nur zur Bestätigung der Anfrage verwendet)",
        "field_contact_phone": "Telefon (optional, wird auf der Seite angezeigt, falls angegeben)",
        "consent": "Ich bestätige, die oben ausgewählte im Register eingetragene Person zu sein, oder ordnungsgemäss bevollmächtigt zu sein, in ihrem Namen zu handeln.",
        "submit": "Anfrage senden",
        "submitting": "Wird gesendet...",
        "success_title": "Anfrage gesendet",
        "success_text": "Wir melden uns innerhalb weniger Tage per E-Mail, um Ihre Seite vor der Veröffentlichung zu bestätigen.",
        "error_generic": "Ein Fehler ist aufgetreten. Versuchen Sie es erneut oder schreiben Sie uns an contact@legatis.ch.",
        "error_missing_match": "Bitte wählen Sie zuerst Ihren Eintrag im Register aus.",
        "error_missing_photo": "Ein Foto ist erforderlich.",
        "error_missing_consent": "Bitte bestätigen Sie Ihre berufliche Identität.",
    },
    "it": {
        "title": "Richiedi la tua vetrina gratuita",
        "intro": "Una pagina personale, ospitata su Legatis, da mettere in evidenza sul vostro profilo Google Business o sul vostro sito. Gratuita, senza impegno. Verifichiamo ogni richiesta prima della pubblicazione.",
        "step1_title": "1. Trovate la vostra scheda",
        "step1_help": "Cercate il vostro nome per collegare la vetrina alla vostra iscrizione nel registro ufficiale (obbligatorio).",
        "step1_search_placeholder": "Il vostro nome...",
        "step1_selected": "Scheda selezionata:",
        "step1_change": "Cambia",
        "step1_not_found": "Non trovate la vostra scheda? Scriveteci a contact@legatis.ch, il vostro Cantone potrebbe non essere ancora coperto.",
        "step2_title": "2. Scegliete uno stile",
        "step2_help": "Potrete cambiarlo in seguito, gratuitamente, basta scriverci.",
        "step3_title": "3. Personalizzate la vostra pagina",
        "field_photo": "Foto professionale",
        "field_photo_help": "Formato JPG o PNG, massimo 2 MB.",
        "field_role_titre": "Titolo professionale (facoltativo)",
        "field_role_titre_placeholder": "Es.: Avvocata associata, specialista FSA in diritto del lavoro",
        "field_accroche": "Frase d'effetto (breve)",
        "field_accroche_placeholder": "Es.: Difendervi con rigore e umanità.",
        "field_bio": "Presentazione (testo libero)",
        "field_bio_placeholder": "Percorso, approccio, ciò che vi distingue...",
        "field_citation": "Citazione o filosofia professionale (facoltativo)",
        "field_specialites": "I vostri ambiti di competenza",
        "field_distinctions": "Riconoscimenti o pubblicazioni (facoltativo, uno per riga)",
        "field_site_web": "Sito web (facoltativo)",
        "field_linkedin": "LinkedIn (facoltativo)",
        "field_instagram": "Instagram (facoltativo)",
        "field_accent": "Colore d'accento",
        "field_photo_frame": "Cornice della foto",
        "field_style_titres": "Stile dei titoli",
        "step4_title": "4. Informazioni pratiche (facoltativo)",
        "step4_help": "Queste informazioni compaiono sulla vostra pagina per facilitare il contatto. Lasciate vuoto ciò che non volete mostrare.",
        "field_adresse": "Indirizzo dello studio",
        "field_adresse_placeholder": "Via, numero, NPA, città",
        "field_horaires": "Orari di apertura",
        "field_horaires_placeholder": "Es.: Lu-Ve 8:30-18:00, su appuntamento",
        "field_whatsapp": "WhatsApp",
        "field_whatsapp_placeholder": "+41 79 000 00 00",
        "field_rdv_url": "Link per prendere appuntamento",
        "field_rdv_url_placeholder": "https://calendly.com/...",
        "field_video_url": "Video di presentazione (YouTube o Vimeo)",
        "field_video_url_placeholder": "https://www.youtube.com/watch?v=...",
        "field_galerie": "Foto supplementari (studio, team)",
        "field_galerie_placeholder": "Un URL immagine per riga, massimo 4",
        "step5_title": "5. I vostri contatti",
        "field_contact_email": "Email di contatto (usata solo per validare la richiesta)",
        "field_contact_phone": "Telefono (facoltativo, mostrato sulla pagina se indicato)",
        "consent": "Confermo di essere la persona iscritta nel registro selezionata sopra, o di essere debitamente incaricato/a di agire per suo conto.",
        "submit": "Invia la mia richiesta",
        "submitting": "Invio in corso...",
        "success_title": "Richiesta inviata",
        "success_text": "Vi ricontatteremo via email entro qualche giorno per validare la vostra pagina prima della pubblicazione.",
        "error_generic": "Si è verificato un errore. Riprovate o scriveteci a contact@legatis.ch.",
        "error_missing_match": "Selezionate la vostra scheda nel registro prima di continuare.",
        "error_missing_photo": "È richiesta una foto.",
        "error_missing_consent": "Confermate la vostra identità professionale.",
    },
    "en": {
        "title": "Request your free showcase page",
        "intro": "A personal page, hosted on Legatis, that you can feature on your Google Business Profile or your own website. Free, no commitment. We review every request before publishing.",
        "step1_title": "1. Find your listing",
        "step1_help": "Search your name to link the showcase page to your listing in the official register (required).",
        "step1_search_placeholder": "Your name...",
        "step1_selected": "Selected listing:",
        "step1_change": "Change",
        "step1_not_found": "Can't find your listing? Email us at contact@legatis.ch, your canton may not be covered yet.",
        "step2_title": "2. Choose a style",
        "step2_help": "You can change it later, for free, just email us.",
        "step3_title": "3. Customise your page",
        "field_photo": "Professional photo",
        "field_photo_help": "JPG or PNG, 2 MB maximum.",
        "field_role_titre": "Professional title (optional)",
        "field_role_titre_placeholder": "E.g.: Partner, SBA-certified specialist in employment law",
        "field_accroche": "Short tagline",
        "field_accroche_placeholder": "E.g.: Defending your interests with rigour and humanity.",
        "field_bio": "Bio (free text)",
        "field_bio_placeholder": "Background, approach, what sets you apart...",
        "field_citation": "Quote or professional philosophy (optional)",
        "field_specialites": "Your practice areas",
        "field_distinctions": "Awards or publications (optional, one per line)",
        "field_site_web": "Website (optional)",
        "field_linkedin": "LinkedIn (optional)",
        "field_instagram": "Instagram (optional)",
        "field_accent": "Accent colour",
        "field_photo_frame": "Photo frame",
        "field_style_titres": "Heading style",
        "step4_title": "4. Practical information (optional)",
        "step4_help": "This information appears on your page to make it easier for clients to reach you. Leave blank anything you don't want to show.",
        "field_adresse": "Office address",
        "field_adresse_placeholder": "Street, number, postcode, city",
        "field_horaires": "Opening hours",
        "field_horaires_placeholder": "E.g.: Mon-Fri 8:30am-6pm, by appointment",
        "field_whatsapp": "WhatsApp",
        "field_whatsapp_placeholder": "+41 79 000 00 00",
        "field_rdv_url": "Booking link",
        "field_rdv_url_placeholder": "https://calendly.com/...",
        "field_video_url": "Introduction video (YouTube or Vimeo)",
        "field_video_url_placeholder": "https://www.youtube.com/watch?v=...",
        "field_galerie": "Additional photos (office, team)",
        "field_galerie_placeholder": "One image URL per line, 4 maximum",
        "step5_title": "5. Your contact details",
        "field_contact_email": "Contact email (used only to confirm the request)",
        "field_contact_phone": "Phone (optional, shown on the page if provided)",
        "consent": "I confirm I am the registered person selected above, or duly authorised to act on their behalf.",
        "submit": "Send my request",
        "submitting": "Sending...",
        "success_title": "Request sent",
        "success_text": "We'll get back to you by email within a few days to confirm your page before publishing.",
        "error_generic": "Something went wrong. Try again or email us at contact@legatis.ch.",
        "error_missing_match": "Please select your listing from the register before continuing.",
        "error_missing_photo": "A photo is required.",
        "error_missing_consent": "Please confirm your professional identity.",
    },
}


# Donnee d'exemple pour les pages de demonstration (gen_vitrine_previews),
# utilisees comme etat initial de l'apercu live dans le formulaire de
# demande. Jamais une vraie personne -- entierement fictif.
PREVIEW_SAMPLE = {
    "fr": {
        "nom_complet": "Camille Fontaine",
        "role_titre": "Avocate associee, specialiste FSA en droit du travail",
        "accroche": "Defendre vos droits avec rigueur, sans jamais perdre de vue l'humain.",
        "bio": "Apres dix ans de pratique a Geneve, j'accompagne particuliers et entreprises dans leurs litiges de droit du travail et de droit des contrats, avec une attention particuliere portee a la clarte de la communication tout au long de la procedure.",
        "citation": "Le droit n'a de sens que s'il reste accessible a celles et ceux qu'il est cense proteger.",
        "ville": "Geneve",
        "canton_name": "Geneve",
        "langues": ["Francais", "Anglais"],
        "specialites_sample": ["droit-du-travail", "droit-des-contrats"],
        "distinctions": ["Barreau de Geneve depuis 2014"],
        "adresse": "12 rue du Rhone, 1204 Geneve",
        "horaires": "Lu-Ve 8h30-18h00, sur rendez-vous",
        "whatsapp": "+41 79 000 00 00",
        "rdv_url": "https://calendly.com/exemple",
        "video_url": "",
        "galerie": [],
    },
    "de": {
        "nom_complet": "Camille Fontaine",
        "role_titre": "Partneranwaeltin, SAV-Fachanwaeltin Arbeitsrecht",
        "accroche": "Ihre Rechte mit Sorgfalt vertreten, ohne den Menschen aus den Augen zu verlieren.",
        "bio": "Nach zehn Jahren Praxis in Genf begleite ich Privatpersonen und Unternehmen bei arbeits- und vertragsrechtlichen Streitigkeiten, mit besonderem Augenmerk auf klare Kommunikation waehrend des gesamten Verfahrens.",
        "citation": "Recht ergibt nur dann Sinn, wenn es fuer jene zugaenglich bleibt, die es schuetzen soll.",
        "ville": "Genf",
        "canton_name": "Genf",
        "langues": ["Franzoesisch", "Englisch"],
        "specialites_sample": ["droit-du-travail", "droit-des-contrats"],
        "distinctions": ["Anwaltskammer Genf seit 2014"],
        "adresse": "Rue du Rhone 12, 1204 Genf",
        "horaires": "Mo-Fr 8.30-18.00 Uhr, nach Vereinbarung",
        "whatsapp": "+41 79 000 00 00",
        "rdv_url": "https://calendly.com/exemple",
        "video_url": "",
        "galerie": [],
    },
    "it": {
        "nom_complet": "Camille Fontaine",
        "role_titre": "Avvocata associata, specialista FSA in diritto del lavoro",
        "accroche": "Difendere i vostri diritti con rigore, senza mai perdere di vista la persona.",
        "bio": "Dopo dieci anni di pratica a Ginevra, affianco privati e aziende nelle controversie di diritto del lavoro e dei contratti, con particolare attenzione alla chiarezza della comunicazione durante tutta la procedura.",
        "citation": "Il diritto ha senso solo se resta accessibile a chi e chiamato a proteggere.",
        "ville": "Ginevra",
        "canton_name": "Ginevra",
        "langues": ["Francese", "Inglese"],
        "specialites_sample": ["droit-du-travail", "droit-des-contrats"],
        "distinctions": ["Ordine degli avvocati di Ginevra dal 2014"],
        "adresse": "Rue du Rhone 12, 1204 Ginevra",
        "horaires": "Lu-Ve 8:30-18:00, su appuntamento",
        "whatsapp": "+41 79 000 00 00",
        "rdv_url": "https://calendly.com/exemple",
        "video_url": "",
        "galerie": [],
    },
    "en": {
        "nom_complet": "Camille Fontaine",
        "role_titre": "Partner, SBA-certified specialist in employment law",
        "accroche": "Defending your rights with rigour, without ever losing sight of the person.",
        "bio": "After ten years of practice in Geneva, I support individuals and businesses through employment and contract law disputes, with particular attention to clear communication throughout the process.",
        "citation": "The law only makes sense if it stays accessible to those it is meant to protect.",
        "ville": "Geneva",
        "canton_name": "Geneva",
        "langues": ["French", "English"],
        "specialites_sample": ["droit-du-travail", "droit-des-contrats"],
        "distinctions": ["Geneva Bar Association since 2014"],
        "adresse": "12 rue du Rhone, 1204 Geneva",
        "horaires": "Mon-Fri 8:30am-6pm, by appointment",
        "whatsapp": "+41 79 000 00 00",
        "rdv_url": "https://calendly.com/example",
        "video_url": "",
        "galerie": [],
    },
}
