# -*- coding: utf-8 -*-
# Donnees brutes transcrites depuis ar.ch/gerichte/obergericht/anwaltsregister-oeffentliche-urkundspersonen
# (registre officiel du canton d'Appenzell Rhodes-Exterieures, consulte le 2026-07-29)
AR_RAW = [
    ("Anwander Christoph", "Advokaturbüro Christoph Anwander-Walser, Bahnhofstr. 21, 9100 Herisau"),
    ("Birchler Martin, Fürsprecher", "Industriestrasse 28, 9100 Herisau"),
    ("Bötschi Christian, lic. iur.", "Speicherstrasse 1536, 9053 Teufen"),
    ("Brunett Flurina, M.A. HSG in Law", "Brunett Rechtsanwälte, St. Gallerstrasse 57, 9100 Herisau"),
    ("Camavdic Benjamin, M.A. HSG in Law", "Novalex Rechtsanwälte AG, Hauptstrasse 39, 9053 Teufen"),
    ("Caroni Andrea, Prof. Dr. iur., MPA", "ME Advocat AG, Poststrasse 1, 9100 Herisau"),
    ("Cavelti Fidel, lic. iur.", "Cavelti & Wernli, Kasernenstrasse 1, 9100 Herisau"),
    ("Eberle Vera, M.A. HSG in Law", "Novalex Rechtsanwälte AG, Hauptstrasse 39, 9053 Teufen"),
    ("Eggenberger Heinrich, lic. iur.", "AES Rechtsanwälte, Paradiesweg 2, 9410 Heiden"),
    ("Ehrenzeller Daniel, lic. iur.", "Engelgasse 214, 9053 Teufen"),
    ("Giuliani Fabian, M.A. HSG in Law", "Novalex Rechtsanwälte AG, Hauptstrasse 39, 9053 Teufen"),
    ("Giuliani Piergiorgio, lic. iur.", "schmid, giuliani, Rechtsanwälte, Hauptstrasse 39, 9053 Teufen"),
    ("Grosjean Louis, lic. iur.", "Polartis Advokatur, Kirchrain 20, 9042 Speicher"),
    ("Kehl Simon, lic. iur.", "Rothaldenstrasse 21, 9055 Bühler"),
    ("Kohler Sarah, lic. iur. Fürsprecherin", "Novalex Rechtsanwälte AG, Hauptstrasse 39, 9053 Teufen"),
    ("Langenauer Christoph, lic. iur.", "Hinterwies 44, 9042 Speicher"),
    ("Ludwig Felix, lic. iur.", "ME Advocat AG, Poststrasse 1, 9100 Herisau"),
    ("Müller-Gerteis Anja, Dr. iur.", "Bachstelzenweg 3, 9410 Heiden"),
    ("Osterwalder Nadine, lic. iur.", "ME Advocat AG, Poststrasse 1, 9100 Herisau"),
    ("Pavataj Burim, M.A. HSG in Law and Economics", "Novalex Rechtsanwälte AG, Hauptstrasse 39, 9053 Teufen"),
    ("Schmid Hanswalter, lic. iur. et lic. oec.", "schmid, giuliani, Rechtsanwälte, Hauptstrasse 39, 9053 Teufen"),
    ("Sieber Otmar, lic. iur.", "Nideren 34, 9043 Trogen"),
    ("Simoni Gazmend, M.A. HSG in Law", "Novalex Rechtsanwälte AG, Hauptstrasse 39, 9053 Teufen"),
    ("Steuri Manuel, MLaw UZH", "SteuriFisch AG, Ebni 3, 9053 Teufen"),
    ("Sutter Peter, Dr. iur.", "Gemeindeweg 4, 9410 Heiden"),
    ("Thier Markus, Dr. iur.", "Bahnhofstrasse 4, 9100 Herisau"),
    ("Vadas Mattea, MLaw", "Polartis Advokatur, Kirchrain 20, 9042 Speicher"),
    ("Walker Timon, lic. iur.", "Advokaturbüro Walker, Unterdorf 5, 9043 Trogen"),
    ("Wernli Jürg, lic. iur. et lic. oec.", "Cavelti & Wernli, Kasernenstrasse 1, 9100 Herisau"),
]
