# -*- coding: utf-8 -*-
# Donnees brutes transcrites depuis baselland.ch/politik-und-behorden/gerichte/anwaltsregister
# (registre officiel du canton de Bale-Campagne, consulte le 2026-07-29)
BL_RAW = [
    ("Achermann Alexander, Dr. iur.", "Advokatur und Notariat Dr. Alex Achermann, Haus zur alten Waage, Hauptstrasse 1, 4102 Binningen"),
    ("Ackermann Fioroni Susanne, lic. iur.", "Advokatur Ackermann Mathys, Spittelerhof, Kasernenstrasse 22a, Postfach 569, 4410 Liestal"),
    ("Aeschlimann Sabine, Dr. iur.", "Janiak Freivogel Schweighauser, von Wartburg, Advokaturbüro, Hauptstrasse 104, 4102 Binningen"),
    ("Akarsu-Mermer Aysel, Ass. iur.", "Advokatur und Rechtsberatung TRIAS AG, Salinenstrasse 25, 4133 Pratteln"),
    ("Albrecht Marco, lic. iur.", "Advokaturbüro Albrecht I Riedo I Anwander, Hauptstrasse 54, 4132 Muttenz"),
    ("Anwander Dominique, MLaw", "Advokaturbüro Albrecht I Riedo I Anwander, Hauptstrasse 54, 4132 Muttenz"),
    ("Baader Caspar, lic. iur.", "BAADER Rechtsanwälte AG, Ochsengasse 19/21, 4460 Gelterkinden"),
    ("Baader Hannes, MA. HSG", "BAADER Rechtsanwälte AG, Ochsengasse 19/21, 4460 Gelterkinden"),
    ("Baader Michael, lic. iur.", "BAADER Rechtsanwälte AG, Ochsengasse 19/21, 4460 Gelterkinden"),
    ("Baader Samuel, MLaw", "BAADER Rechtsanwälte AG, Ochsengasse 19/21, 4460 Gelterkinden"),
    ("Bächli Michael, lic. iur.", "Baechli GmbH, Schanzgasse 11a, 4107 Ettingen"),
    ("Bai Alain, Dr. iur.", "LEXPARTNERS., Kirchplatz 16, 4132 Muttenz"),
    ("Baumgartner Nico Serge, lic. iur.", "Advokatur Landi Ruckstuhl Giess Tzikas Baumgartner, Oberwilerstrasse 3, Postfach 312, 4123 Allschwil"),
    ("Bay Hanna Christa, MLaw", "Advokatur Schweighauser von Wartburg Aeschlimann Maier, Hauptstrasse 104, 4102 Binningen"),
    ("Belser Marco, MLaw", "Advokatur Roth, Zeughausplatz 34, Postfach, 4410 Liestal"),
    ("Berger Simon, lic. iur.", "Advokatur zum Thurgauerhof, Büchelistr. / Lindenstr. 2, Postfach, 4410 Liestal"),
    ("Bifl Daniela", "Hohenrainstrasse 12c, 4133 Pratteln"),
    ("Bläsi Stephan, lic. iur.", "Holeerebenweg 16, 4123 Allschwil"),
    ("Blattner Michael Robert, MLaw", "Advokatur Sissach, Bischofsteinweg 15, Postfach 182, 4450 Sissach"),
    ("Bloch Jan Marc, MLaw", "Cron Bloch Schmid, Notariat & Advokatur, Hauptstrasse 68, Postfach 127, 4132 Muttenz"),
    ("Borer René, lic. iur.", "Advokaturbüro Borer, Delsbergstrasse 14, 4242 Laufen"),
    ("Borter Daniel, lic. iur.", "Rebgasse 11, 4434 Hölstein"),
    ("Bossert Katharina Elvira, lic. iur.", "Advokatur am Fischmarkt, Fischmarkt 12, 4410 Liestal"),
    ("Bräutigam Christian Wolfgang, MLaw", "Advokatur zum Schloss, Schlossgasse 1, 4102 Binningen"),
    ("Brand Irmgard, lic. iur.", "Oberemattstrasse 56, 4133 Pratteln"),
    ("Breitenmoser Stephan, Prof. Dr. iur.", "LEXPARTNERS., Advokaten, Kirchplatz 16, 4132 Muttenz"),
    ("Brodbeck Peter, lic. iur.", "Birmannstrasse 12, 4410 Liestal"),
    ("Bron Véronique, lic. iur.", "Advokatur Enderle, Felix, Haidlauf, Schmid, Hauptstrasse 8, Postfach 732, 4153 Reinach 1"),
    ("Brunner André, lic. iur.", "Hauptstrasse 55 / Cheesmeyerhaus, Postfach 136, 4450 Sissach"),
    ("Bürgi Silvio, MLaw", "Advokatur und Notariat Neidhart Joset Bürgi, Gitterlistrasse 8, Postfach 215, 4410 Liestal"),
    ("Burgunder Joël Cedric, MLaw", "Advokatur Stoll Schulthess Partner, Hauptstrasse 12, Postfach 811, 4153 Reinach"),
    ("Butz Jacques, lic.iur.", "Butz Corvini Sigel, Advokatur & Mediation, Dorfplatz 2, Postfach, 4123 Allschwil"),
    ("Christen Thomas, Dr. iur.", "Advokatur zum Thurgauerhof, Büchelistr. / Lindenstr. 2, Postfach, 4410 Liestal"),
    ("Corvini Ivo Lorenzo, Dr. iur.", "Butz Corvini Sigel, Advokatur & Mediation, Dorfplatz 2, Postfach, 4123 Allschwil"),
    ("Cron-Nussberger Laura, MLaw", "Cron Bloch Schmid Notariat + Advokatur KLG, Hauptstrasse 68, 4132 Muttenz"),
    ("Delbrück Gottlieb G., Dr. iur.", "Batteriestrasse 17, 4103 Bottmingen"),
    ("Dettwiler Heinz, lic. iur.", "In der Erlen 1, 4438 Langenbruck"),
    ("Duss Jacobi Vanessa Caroline, Dr. iur.", "Lexperts Advokatur, Kasernenstrasse 22, 4410 Liestal"),
    ("Elbert Bodo, lic. iur.", "Waldstrasse 62, 4144 Arlesheim"),
    ("Enderle Christof, lic. iur", "Advokatur Enderle, Felix, Haidlauf, Schmid, Hauptstrasse 8, Postfach 732, 4153 Reinach"),
    ("Enderle Felix, lic. iur", "Binningerstrasse 193A, 4123 Allschwil"),
    ("Epple Peter Martin, MLaw", "BIRSLEX Advokatur, Emil Frey-Strasse 85, 4142 Münchenstein"),
    ("Erhart Dominique, lic. iur.", "Erhart Rechtsanwälte & Notariat, Konsumstrasse 1, Postfach, 4104 Oberwil"),
    ("Eschbach Robin, MLaw", "Advokatur am Fischmarkt, Fischmarkt 12, 4410 Liestal"),
    ("Felix Roman, lic. iur.", "Advokatur Enderle, Felix, Haidlauf, Schmid, Hauptstrasse 8, Postfach 732, 4153 Reinach"),
    ("Fischer Bernhard, lic. iur.", "Advokatur Sissach, Postgasse 9, Postfach 182, 4450 Sissach"),
    ("Fluri Fabian Andres, MLaw", "Advokatur im Gstad, Tramstrasse 55, 4142 Münchenstein"),
    ("Frei-Schefer Erwin, lic. iur.", "Advokatur, Surbaumstrasse 2, Postfach 157, 4153 Reinach"),
    ("Freivogel Elisabeth, lic. iur.", "Janiak Freivogel Schweighauser, von Wartburg, Advokaturbüro, Hauptstrasse 104, 4102 Binningen"),
    ("Frey-Napier Judith, lic. iur.", "BAADER Rechtsanwälte AG, Ochsengasse 19/21, 4460 Gelterkinden"),
    ("Furger Valery Lee, MLaw", "BIRSLEX Advokatur, Emil Frey-Strasse 85, 4142 Münchenstein"),
    ("Fürstenberger Beat, Dr. iur.", "Faissgärtli 17, Postfach 330, 4144 Arlesheim"),
    ("Gantner Angela, lic. iur.", "Advokatur Angela Gantner, Kasernenstrasse 22a, 4410 Liestal"),
    ("Gantner Reto, lic. iur.", "Advokatur, Kasernenstrasse 22a, 4410 Liestal"),
    ("Giess Gabriel, MLaw", "Advokatur Landi Ruckstuhl Giess Tzikas Baumgartner, Oberwilerstrasse 3, Postfach 312, 4123 Allschwil"),
    ("Girod Carole, MLaw", "Baader Rechtsanwälte, Ochsengasse 19/21, 4460 Gelterkinden"),
    ("Glauser David, lic. iur.", "LEXPARTNERS., Kirchplatz 16, 4132 Muttenz"),
    ("Gremmelspacher-Rutz Simone, MLaw, Advokatin", "Advokatur + Mediation Simone Gremmelspacher-Rutz, Spinnlerstrasse 2, 4410 Liestal"),
    ("Grob Urs, lic. iur.", "Advokatur Stadthof AG, Hauptstrasse 47, 4153 Reinach"),
    ("Gubler Borer Kristin, lic. iur.", "Vorstadt - Delsbergerstrasse 14, 4242 Laufen"),
    ("Gutzwiller Bruno, Dr. iur.", "Kirchrain 2, Postfach, 4106 Therwil"),
    ("Gutzwiller Emmerth Elisabeth, lic. iur.", "Enderle, Felix, Haidlauf, Schmid, Advokatur, Hauptstrasse 8, Postfach 732, 4153 Reinach"),
    ("Haidlauf Christian, lic. iur.", "Advokatur Enderle, Felix, Haidlauf, Schmid, Hauptstrasse 8, Postfach 732, 4153 Reinach"),
    ("Häner Philipp, lic. iur.", "Advokatur & Rechtsberatung TRIAS AG, Salinenstrasse 25, 4133 Pratteln"),
    ("Hänggi Nicolas, MLaw", "Advokatur Nicolas Hänggi, Kasernenstrasse 22a, 4410 Liestal"),
    ("Häring Adolf, Dr. iur.", "Hauptstrasse 77, Postfach 343, 4132 Muttenz"),
    ("Haubensak Vanessa Caroline, Dr. iur.", "Advokatur Stoll Schulthess Partner, Hauptstrasse 12, 4153 Reinach"),
    ("Heinzelmann Alexander, lic. iur.", "Advokaturbüro Heinzelmann & Levy, Wasserturmplatz 3, Postfach 349, 4410 Liestal"),
    ("Helfenfinger Daniel Urs, lic. iur. et lic. rer. pol.", "Advokatur & Notariat Helfenfinger, Bahnhofstrasse 6, 4242 Laufen"),
    ("Héritier Patrick, lic. iur.", "Hafenrainstrasse 101, 4104 Oberwil"),
    ("Hess Helena, Dr. iur.", "Schulstrasse 23, Postfach 406, 4132 Muttenz 1"),
    ("Hill Noémie, Dr. iur.", "hilladvokatur, Hardstrasse 18, 4132 Muttenz"),
    ("Hindermann Fluri Heidi, lic. iur.", "Tramstrasse 55, 4142 Münchenstein"),
    ("Hofmann-Schmid Gabriele, Dr. iur.", "Legalcoaching, Dombergweg 14, 4423 Hersberg"),
    ("Huber Matthias, MLaw", "KIPFERHUBER Advokatur, Grienmattweg 1, Postfach, 4450 Sissach"),
    ("Huber Olivier Yves, lic. iur.", "Advokatur Huber, Büsserachstrasse 2, Postfach 22, 4246 Wahlen b. Laufen"),
    ("Hug Lisa Cécile, MLaw", "Advokatur Schweighauser von Wartburg Aeschlimann Maier, Hauptstrasse 104, 4102 Binningen"),
    ("Ivanov Daniel, Dr. iur.", "Advokatur An der Au, Bärenweg 14, 4153 Reinach"),
    ("Jeanneret Claude, Dr. iur.", "notavis Jeanneret & Lutz, Bahnhofstrasse 16, 4144 Arlesheim"),
    ("Jeanneret Joel Patrice, MLaw", "Advokatur Stoll Schulthess Partner, Hauptstrasse 12, 4153 Reinach"),
    ("Jermann Barbara, lic. iur.", "Enderle, Felix, Haidlauf, Schmid, Advokatur, Hauptstrasse 8, Postfach 732, 4153 Reinach"),
    ("Jermann Jgnaz, Dr. iur.", "Advokaturbüro Dr. Jermann, Röschenzstrasse 23, 4242 Laufen"),
    ("Jermann Nicolas, MLaw", "Advokatur Stoll Schulthess Partner, Hauptstrasse 12, 4153 Reinach"),
    ("Joset Alain, lic. iur.", "Advokatur und Notariat Neidhart Joset Bürgi, Gitterlistrasse 8, Postfach 215, 4410 Liestal"),
    ("Kipfer-Berger Jonas Michael, Dr. iur.", "KIPFERHUBER Advokatur, Grienmattweg 1, Postfach, 4450 Sissach"),
    ("Kopp Andreas Matthias, lic. iur.", "LEXPARTNERS., Kirchplatz 16, 4132 Muttenz"),
    ("Kunz Michael, lic. iur.", "Michael Kunz Advokat, Schulgasse 8, 4455 Zunzgen"),
    ("Küng Christoph, lic. iur.", "Advokatur Lehner, Trüeb & Küng, Militärstrasse 17, 4410 Liestal"),
    ("Küng Ernst, Dr. iur.", "Linsi, Küng, Levy, Wüthrich, Güterstrasse 1, Postfach 1607, 4133 Pratteln"),
    ("Laishevtseva Anna, MLaw", "KIPFERHUBER Advokatur, Grienmattweg 1, Postfach, 4450 Sissach"),
    ("Landi Annalisa, lic. iur.", "Advokatur Landi Ruckstuhl Giess Tzikas Baumgartner, Oberwilerstrasse 3, Postfach 312, 4123 Allschwil"),
    ("Laubscher Roman, lic. iur.", "Zeller Dettwiler Advokatur & Notariat, Wasserturmplatz 3, 4410 Liestal"),
    ("Lehner Beat, lic. iur.", "Advokatur Lehner, Trüeb & Küng, Militärstrasse 17, 4410 Liestal"),
    ("Levy Daniel, lic. iur.", "Advokaturbüro Heinzelmann & Levy, Wasserturmplatz 3, Postfach 349, 4410 Liestal"),
    ("Lopez Garcia Sonia, Lda.", "Advokatur & Rechtsberatung TRIAS AG, Salinenstrasse 25, 4133 Pratteln"),
    ("Lopez Molina Jose Francisco. Ldo.", "advoSpanien, Muttenzerstrasse 37, Postfach, 4133 Pratteln"),
    ("Maier-Joset Elisabeth Sophia, lic. iur.", "Advokaturbüro Janiak, Freivogel, Schweighauser, von Wartburg, Aeschlimann, Maier, Hauptstrasse 104, 4102 Binningen"),
    ("Mathys-Währer Stefanie, lic. iur.", "Advokatur Ackermann Mathys, Spittelerhof, Kasernenstrasse 22a, Postfach 569, 4410 Liestal"),
    ("Matiaska Natalie, lic. iur.", "Advokatur am Fischmarkt, Fischmarkt 12, 4410 Liestal"),
    ("Mayer Felix, Dr. iur.", "Gassenackerweg 16, 4223 Blauen"),
    ("Meier Cornelia, Dr. iur.", "Stedtli Notariat Liestal, Amtshausgasse 6, 4410 Liestal"),
    ("Meier Soraya, MLaw", "Simon-Vermot & Weber Notariat und Advokatur, Pfeffingerstrasse 19, 4153 Reinach BL"),
    ("Messerli Rafael Araujo, MLaw", "LEXPARTNERS., Kirchplatz 16, 4132 Muttenz"),
    ("Metz Markus, Dr. iur.", "Dr. Metz Advokatur, Auf der Hueb 6, 4102 Binningen"),
    ("Meyer Helena, MLaw", "Advokatur Landi Ruckstuhl Giess Tzikas Baumgartner, Oberwilerstrasse 3, Postfach 312, 4123 Allschwil"),
    ("Meyer Peter, Dr. iur.", "Neuwilerstrasse 14, 4104 Oberwil"),
    ("Moser Nicola, Dr. iur.", "LEXPARTNERS., Kirchplatz 16, 4132 Muttenz"),
    ("Moser Silvia, lic. iur.", "Buttertalstrasse 8, 4106 Therwil"),
    ("Mosimann Johannes Claudius, MLaw", "Advokatur Roth, Zeughausplatz 34, Postfach, 4410 Liestal"),
    ("Näf Joël, MLaw", "Advokatur von Blarer, Anton von Blarerweg 2, 4147 Aesch BL"),
    ("Noelpp Christoph Friedrich, Dr. iur.", "Advokatur Dr. C. Noelpp, Erlenstrasse 31, 4106 Therwil"),
    ("Odermatt Aline Simone, MLaw", "BIRSLEX Advokatur, Emil-Frey Strasse 85, 4142 Münchenstein"),
    ("Olah Philipp André, lic. iur.", "Poststrasse 3, Postfach, 4410 Liestal"),
    ("Oppliger Sven, Dr. iur.", "Advokatur & Mediation Dr. Oppliger, Weichselmattstrasse 11, 4103 Bottmingen"),
    ("Pecorelli Fabio Gerardo, MLaw", "Advokatur Stadthof AG, Hauptstrasse 47, 4153 Reinach"),
    ("Pfulg José, lic. iur.", "Notariat & Advokatur Pfulg, Hauptstrasse 112, 4450 Sissach"),
    ("Polatli Ozan, lic. iur.", "ADVOKATUR POLATLI, Rathausstrasse 68, Postfach, 4410 Liestal"),
    ("Ramseier Thomas, Dr. iur.", "LEXPARTNERS, Advokaten, Kirchplatz 16, Postfach 916, 4132 Muttenz 1"),
    ("Ranert Georg, MLaw", "Advokaturbüro Ranert, Schulstrasse 23, 4132 Muttenz"),
    ("Reich Markus, Dr. iur.", "Reich Fürstenberger, Advokatur und Notariat, Faissgärtli 17, 4144 Arlesheim"),
    ("Rey Laura, lic. iur.", "Christoph Merian-Ring 11, 4153 Reinach BL"),
    ("Riedo Pascal, lic. iur.", "Advokaturbüro Albrecht I Riedo I Anwander, Hauptstrasse 54, 4132 Muttenz"),
    ("Riggenbach Dieter, Dr. iur.", "Lupsingerstrasse 15, 4417 Ziefen"),
    ("Rosenthaler Simon Thomas, lic. iur.", "Advokatur Rosenthaler, Holeerain 4, 4102 Binningen"),
    ("Roth Dieter, lic. iur.", "Advokatur Roth, Zeughausplatz 34, Postfach, 4410 Liestal"),
    ("Roth Monika, Prof. Dr. iur.", "Gartenstrasse 20, 4102 Binningen 1"),
    ("Ruckstuhl Niklaus, Dr. iur.", "Advokatur Landi Ruckstuhl Giess Tzikas Baumgartner, Oberwilerstrasse 3, Postfach 312, 4123 Allschwil"),
    ("Rufer-Hohl Nicole, lic. iur.", "Advokatur Roth, Zeughausplatz 34, Postfach 375, 4410 Liestal"),
    ("Rufi Werner, lic. iur.", "Advokaturbüro Rufi und Partner, Schmiedengasse 7, Postfach, 4104 Oberwil"),
    ("Rupp Philipp, lic. iur.", "Rupp Rechtsanwälte, Kunimattweg 14, 4133 Pratteln"),
    ("Schermbach Michael Karl Gerhard, lic. iur.", "Strengigartenweg 31, 4123 Allschwil"),
    ("Scheuplein Beatrix, MLaw", "Advokatur Roth, Zeughausplatz 34, Postfach, 4410 Liestal"),
    ("Schmid Adrian, lic. iur.", "Advokatur Enderle, Felix, Haidlauf, Schmid, Hauptstrasse 8, Postfach 732, 4153 Reinach"),
    ("Schmid Andrea, lic. iur.", "Cron Bloch Schmid, Notariat + Advokatur, Hauptstrasse 68, Postfach 127, 4132 Muttenz"),
    ("Schneider Stefanie, MLaw", "Advokatur Stadthof AG, Hauptstrasse 47, 4153 Reinach"),
    ("Schödler Patricia, MLaw", "advokatur schödler, Zelgliweg 3, 4452 Itingen"),
    ("Schnyder-Kienast Salome, Dr. iur.", "Konsumstrasse 1, 4104 Oberwil"),
    ("Schulthess Stefan, lic. iur.", "Advokatur Stoll Schulthess Partner, Hauptstrasse 12, 4153 Reinach"),
    ("Schweighauser Jonas, Dr. iur.", "Janiak Freivogel Schweighauser, von Wartburg, Advokaturbüro, Hauptstrasse 104, 4102 Binningen"),
    ("Schweizer Simon E., Dr. iur.", "Hauptstrasse 40, 4450 Sissach"),
    ("Seger Dominique, Dr. iur.", "c/o Nadine Grieder, Advokatin und Notarin, Hauptstrasse 1, 4102 Binningen"),
    ("Senn Daniel, MLaw", "SENN Advokatur, Burggartenstrasse 40, 4103 Bottmingen"),
    ("Seputyte Agne, MLaw", "ERHART Rechtsanwälte & Notariat, Konsumstrasse 1, 4104 Oberwil"),
    ("Sidler Dimitri, MLaw", "Advokatur Roth, Zeughausplatz 34, Postfach, 4410 Liestal"),
    ("Siegler Kristina, MLaw", "LEXPARTNERS., Kirchplatz 16, 4132 Muttenz"),
    ("Sigel Claudia, lic. iur.", "Butz Corvini Sigel, Advokatur & Mediation, Dorfplatz 2, Postfach, 4123 Allschwil"),
    ("Stemmer Simon, lic.iur.", "STEMMER Advokatur, Oristalstrasse 13, 4410 Liestal"),
    ("Stoll Daniel, lic. iur.", "Advokatur Stoll Schulthess Partner, Hauptstrasse 12, 4153 Reinach"),
    ("Stoll Diego, MLaw", "Advokatur Schweighauser von Wartburg Aeschlimann Maier, Hauptstrasse 104, 4102 Binningen"),
    ("Stutz Désirée, M.A. HSG in Law", "Advokatur Stutz, Amtshausgasse 6, 4410 Liestal"),
    ("Sumi Daniela Sabrina, MLaw", "Advokatur am Fischmarkt, Fischmarkt 12, 4410 Liestal"),
    ("Surber Christoph, lic. iur.", "Rechtsanwalt und eidg. dipl. Steuerexperte, Hauptstrasse 53, Postfach 564, 4127 Birsfelden"),
    ("Tanner Melanie, MLaw", "Anwaltskanzlei Tanner, Geschäftshaus Letten, Fabrikstrasse 2, 4123 Allschwil"),
    ("Treyer Tobias, lic. iur.", "Treyer + Zihlmann Advokatur - Notariat, Hauptstrasse 13, 4144 Arlesheim"),
    ("Treyer-Spitz Brigitte, lic.iur.", "Advokatur Treyer & Zihlmann, Advokatur und Notariat, Hauptstrasse 13, 4144 Arlesheim"),
    ("Troxler Dieter M., Dr. iur.", "ADVOKATUR zum WASSERTURM, Leierweg 265, 4497 Rünenberg"),
    ("Trüeb Ivo, lic. iur.", "Advokatur Lehner, Trüeb & Küng, Militärstrasse 17, 4410 Liestal"),
    ("Trüeb Stephanie, lic. iur.", "Advokatur zum Thurgauerhof, Büchelistr. / Lindenstr. 2, Postfach, 4410 Liestal"),
    ("Tzikas Wicky, MLaw", "Advokatur Landi Ruckstuhl Giess Tzikas Baumgartner, Oberwilerstrasse 3, Postfach 312, 4123 Allschwil"),
    ("Ulrich Silvan, lic. iur.", "Postgasse 3, Postfach 619, 4147 Aesch"),
    ("Urban Gabriele", "Unterer Rebbergweg 116, 4153 Reinach"),
    ("Vecchi Luca, MLaw", "Advokatur Stadthof AG, Hauptstrasse 47, 4153 Reinach"),
    ("von Blarer Dieter, lic. iur.", "Anton von Blarerweg 2, Postfach 629, 4147 Aesch"),
    ("von Wartburg Christian, Dr. iur.", "Janiak Freivogel Schweighauser, von Wartburg, Advokaturbüro, Hauptstrasse 104, 4102 Binningen"),
    ("von Wartburg Spirgi Claudia, lic. iur.", "Janiak Freivogel Schweighauser, von Wartburg, Advokaturbüro, Hauptstrasse 104, 4102 Binningen"),
    ("Wagner Fred Martin, lic. iur.", "Eggstrasse 59, 4402 Frenkendorf"),
    ("Walther Beat, Dr. iur.", "Gärtnerstrasse 6, 4102 Binningen"),
    ("Wassmer Erik, lic. iur.", "Advokatur am Fischmarkt, Fischmarkt 12, 4410 Liestal"),
    ("Weible Claudia, lic. iur.", "RS Rechtsservice AG, Röschenzstrasse 24, 4242 Laufen"),
    ("Wirth Victor, Dr. iur.", "LEXPARTNERS., Kirchplatz 16, 4132 Muttenz"),
    ("Wirz Stefan, Dr. iur.", "Wirz Advokatur, Hauptstrasse 91, 4147 Aesch BL"),
    ("Wirz-Fiechter Ursula, lic. iur.", "Fischer Wirz Advokatur, Gewerbestrasse 10, 4450 Sissach"),
    ("Zeller Roman, lic. iur.", "Zeller Dettwiler Advokatur & Notariat , Wasserturmplatz 3, 4410 Liestal"),
    ("Zihlmann Treyer Barbara, lic. iur.", "Treyer & Zihlmann, Advokatur und Notariat, Hauptstrasse 13, 4144 Arlesheim"),
]
